-- ================================================ĐÂY LÀ CHI NHÁNH 2 - MAY 2==================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- =====================================================
-- TAO USER/SCHEMA TAI MAY2 - CHI NHANH HA NOI
-- =====================================================

CREATE USER MAY2 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO MAY2;
GRANT CREATE TABLE TO MAY2;
GRANT CREATE DATABASE LINK TO MAY2;
GRANT CREATE VIEW TO MAY2;
GRANT CREATE PROCEDURE TO MAY2;
GRANT CREATE TRIGGER TO MAY2;
GRANT CREATE SEQUENCE TO MAY2;

ALTER USER MAY2 QUOTA UNLIMITED ON USERS;
-- =====================================================
-- CREATE TABLE SITE MAY2 - CHI NHANH HA NOI - CN02
-- Schema: MAY2
-- =====================================================

CREATE TABLE MAY2.CHINHANH (
    MACN VARCHAR2(10) PRIMARY KEY,
    TENCN VARCHAR2(100) NOT NULL,
    DIACHI VARCHAR2(200),
    SODIENTHOAI VARCHAR2(15),
    THANHPHO VARCHAR2(50) NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT CK_CN2_CHINHANH_TT CHECK (TRANGTHAI IN ('HOAT_DONG', 'TAM_NGUNG'))
);

CREATE TABLE MAY2.DANHMUC (
    MADM VARCHAR2(10) PRIMARY KEY,
    TENDM VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT CK_CN2_DANHMUC_TT CHECK (TRANGTHAI IN ('HOAT_DONG', 'TAM_NGUNG'))
);

CREATE TABLE MAY2.SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    TENSP VARCHAR2(150) NOT NULL,
    MADM VARCHAR2(10) NOT NULL,
    GIABAN NUMBER(12,0) DEFAULT 0 NOT NULL,
    MOTA VARCHAR2(500),
    NGAYTAO DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN2_SP_DM FOREIGN KEY (MADM) REFERENCES MAY2.DANHMUC(MADM),
    CONSTRAINT CK_CN2_SP_GIA CHECK (GIABAN >= 0)
);

CREATE TABLE MAY2.BIENTHE_SANPHAM (
    MABT VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20) NOT NULL,
    MAU VARCHAR2(50) NOT NULL,
    KICHCO VARCHAR2(20) NOT NULL,
    SKU VARCHAR2(50) UNIQUE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN2_BT_SP FOREIGN KEY (MASP) REFERENCES MAY2.SANPHAM(MASP)
);

CREATE TABLE MAY2.VOUCHER (
    MAVOUCHER VARCHAR2(20) PRIMARY KEY,
    TENVOUCHER VARCHAR2(100) NOT NULL,
    LOAIGIAMGIA VARCHAR2(20) NOT NULL,
    GIATRIGIAM NUMBER(12,0) DEFAULT 0 NOT NULL,
    DIEUKIENTOITHIEU NUMBER(14,0) DEFAULT 0 NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    SOLUONG NUMBER(10,0) DEFAULT 0 NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY2.KHACHHANG_THANHVIEN (
    MAKH VARCHAR2(20) PRIMARY KEY,
    HANGTV VARCHAR2(30) DEFAULT 'DONG' NOT NULL,
    DIEMTICHLUY NUMBER(10,0) DEFAULT 0 NOT NULL,
    NGAYDANGKY DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT CK_CN2_KHTV_HANG CHECK (HANGTV IN ('DONG', 'BAC', 'VANG', 'KIM_CUONG')),
    CONSTRAINT CK_CN2_KHTV_DIEM CHECK (DIEMTICHLUY >= 0)
);

CREATE TABLE MAY2.NHANVIEN_CN02 (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    SODIENTHOAI VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(100) UNIQUE,
    CHUCVU VARCHAR2(50) NOT NULL,
    LUONG NUMBER(12,0) DEFAULT 0 NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN02' NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_LAM' NOT NULL,
    CONSTRAINT FK_CN2_NV_CN FOREIGN KEY (MACN) REFERENCES MAY2.CHINHANH(MACN),
    CONSTRAINT CK_CN2_NV_MACN CHECK (MACN = 'CN02'),
    CONSTRAINT CK_CN2_NV_LUONG CHECK (LUONG >= 0)
);

CREATE TABLE MAY2.DONHANG_CN02 (
    MADH VARCHAR2(30) PRIMARY KEY,
    MAKH VARCHAR2(20) NOT NULL,
    MANV VARCHAR2(20),
    MACN VARCHAR2(10) DEFAULT 'CN02' NOT NULL,
    MAVOUCHER VARCHAR2(20),
    NGAYDAT DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_XAC_NHAN' NOT NULL,
    DIACHINHAN VARCHAR2(200),
    TONGTIENHANG NUMBER(14,0) DEFAULT 0 NOT NULL,
    PHIVANCHUYEN NUMBER(12,0) DEFAULT 0 NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    TONGTHANHTOAN NUMBER(14,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CN2_DH_KHTV FOREIGN KEY (MAKH) REFERENCES MAY2.KHACHHANG_THANHVIEN(MAKH),
    CONSTRAINT FK_CN2_DH_NV FOREIGN KEY (MANV) REFERENCES MAY2.NHANVIEN_CN02(MANV),
    CONSTRAINT FK_CN2_DH_CN FOREIGN KEY (MACN) REFERENCES MAY2.CHINHANH(MACN),
    CONSTRAINT FK_CN2_DH_VC FOREIGN KEY (MAVOUCHER) REFERENCES MAY2.VOUCHER(MAVOUCHER),
    CONSTRAINT CK_CN2_DH_MACN CHECK (MACN = 'CN02'),
    CONSTRAINT CK_CN2_DH_TT CHECK (TRANGTHAI IN ('CHO_XAC_NHAN', 'DANG_XU_LY', 'DANG_GIAO', 'HOAN_THANH', 'DA_HUY'))
);

CREATE TABLE MAY2.CT_DONHANG_CN02 (
    MADH VARCHAR2(30),
    MACN VARCHAR2(10) DEFAULT 'CN02' NOT NULL,
    MABT VARCHAR2(20),
    SOLUONG NUMBER(10,0) NOT NULL,
    DONGIA NUMBER(12,0) NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    THANHTIEN NUMBER(14,0) NOT NULL,
    CONSTRAINT PK_CN2_CTDH PRIMARY KEY (MADH, MABT),
    CONSTRAINT FK_CN2_CTDH_DH FOREIGN KEY (MADH) REFERENCES MAY2.DONHANG_CN02(MADH),
    CONSTRAINT FK_CN2_CTDH_BT FOREIGN KEY (MABT) REFERENCES MAY2.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN2_CTDH_MACN CHECK (MACN = 'CN02'),
    CONSTRAINT CK_CN2_CTDH_SL CHECK (SOLUONG > 0)
);

CREATE TABLE MAY2.THANHTOAN_CN02 (
    MATT VARCHAR2(30) PRIMARY KEY,
    MADH VARCHAR2(30) NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN02' NOT NULL,
    PHUONGTHUC VARCHAR2(50) NOT NULL,
    SOTIEN NUMBER(14,0) NOT NULL,
    NGAYTHANHTOAN DATE DEFAULT SYSDATE,
    MAGIAODICH VARCHAR2(100) UNIQUE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_THANH_TOAN' NOT NULL,
    CONSTRAINT FK_CN2_TT_DH FOREIGN KEY (MADH) REFERENCES MAY2.DONHANG_CN02(MADH),
    CONSTRAINT CK_CN2_TT_MACN CHECK (MACN = 'CN02'),
    CONSTRAINT CK_CN2_TT_PT CHECK (PHUONGTHUC IN ('TIEN_MAT', 'CHUYEN_KHOAN', 'THE', 'VI_DIEN_TU'))
);

CREATE TABLE MAY2.KHO_CN02_TON (
    MACN VARCHAR2(10) DEFAULT 'CN02' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGTON NUMBER(10,0) DEFAULT 0 NOT NULL,
    MUCTONTOITHIEU NUMBER(10,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CN2_KHO_TON PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN2_KHO_TON_BT FOREIGN KEY (MABT) REFERENCES MAY2.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN2_KHO_TON_MACN CHECK (MACN = 'CN02'),
    CONSTRAINT CK_CN2_KHO_TON_SL CHECK (SOLUONGTON >= 0)
);

CREATE TABLE MAY2.KHO_CN02_BANHANG (
    MACN VARCHAR2(10) DEFAULT 'CN02' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGDABAN NUMBER(10,0) DEFAULT 0 NOT NULL,
    NGAYCAPNHAT DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CN2_KHO_BH PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN2_KHO_BH_TON FOREIGN KEY (MACN, MABT) REFERENCES MAY2.KHO_CN02_TON(MACN, MABT),
    CONSTRAINT CK_CN2_KHO_BH_MACN CHECK (MACN = 'CN02'),
    CONSTRAINT CK_CN2_KHO_BH_SL CHECK (SOLUONGDABAN >= 0)
);
-- =====================================================
-- INSERT DATA SITE MAY2 - CN02 - HA NOI
-- Schema: MAY2
-- =====================================================

INSERT INTO MAY2.CHINHANH VALUES ('CN01', 'Chi nhanh TP.HCM', 'Quan 1, TP.HCM', '0901000001', 'TP.HCM', 'HOAT_DONG');
INSERT INTO MAY2.CHINHANH VALUES ('CN02', 'Chi nhanh Ha Noi', 'Quan Hoan Kiem, Ha Noi', '0901000002', 'Ha Noi', 'HOAT_DONG');
INSERT INTO MAY2.CHINHANH VALUES ('CN03', 'Chi nhanh Da Nang', 'Quan Hai Chau, Da Nang', '0901000003', 'Da Nang', 'HOAT_DONG');
INSERT INTO MAY2.CHINHANH VALUES ('CN04', 'Chi nhanh Can Tho', 'Quan Ninh Kieu, Can Tho', '0901000004', 'Can Tho', 'HOAT_DONG');

INSERT INTO MAY2.DANHMUC VALUES ('DM01', 'Ao thun', 'Danh muc ao thun', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM02', 'Ao so mi', 'Danh muc ao so mi', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM03', 'Ao khoac', 'Danh muc ao khoac', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM04', 'Quan dai', 'Danh muc quan dai', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM05', 'Quan ngan', 'Danh muc quan ngan', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM06', 'Vay', 'Danh muc vay', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM07', 'Dam', 'Danh muc dam', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM08', 'Phu kien', 'Danh muc phu kien', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM09', 'Giay dep', 'Danh muc giay dep', 'HOAT_DONG');
INSERT INTO MAY2.DANHMUC VALUES ('DM10', 'Tui xach', 'Danh muc tui xach', 'HOAT_DONG');

INSERT INTO MAY2.SANPHAM (MASP, TENSP, MADM, GIABAN, MOTA, NGAYTAO, TRANGTHAI)
SELECT 'SP' || LPAD(LEVEL, 4, '0'),
       'San pham thoi trang ' || LEVEL,
       'DM' || LPAD(MOD(LEVEL - 1, 10) + 1, 2, '0'),
       100000 + MOD(LEVEL, 50) * 10000,
       'Mo ta san pham ' || LEVEL,
       SYSDATE,
       'DANG_BAN'
FROM DUAL CONNECT BY LEVEL <= 200;

INSERT INTO MAY2.BIENTHE_SANPHAM (MABT, MASP, MAU, KICHCO, SKU, TRANGTHAI)
SELECT 'BT' || LPAD(LEVEL, 4, '0'),
       'SP' || LPAD(MOD(LEVEL - 1, 200) + 1, 4, '0'),
       CASE MOD(LEVEL, 5) WHEN 0 THEN 'DEN' WHEN 1 THEN 'TRANG' WHEN 2 THEN 'DO' WHEN 3 THEN 'XANH' ELSE 'BE' END,
       CASE MOD(LEVEL, 5) WHEN 0 THEN 'S' WHEN 1 THEN 'M' WHEN 2 THEN 'L' WHEN 3 THEN 'XL' ELSE 'XXL' END,
       'SKU_CN02_' || LPAD(LEVEL, 4, '0'),
       'DANG_BAN'
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO MAY2.VOUCHER (
    MAVOUCHER, TENVOUCHER, LOAIGIAMGIA, GIATRIGIAM, DIEUKIENTOITHIEU,
    NGAYBATDAU, NGAYKETTHUC, SOLUONG, TRANGTHAI
)
SELECT 'VC' || LPAD(LEVEL, 3, '0'),
       'Voucher giam gia ' || LEVEL,
       CASE WHEN MOD(LEVEL, 2) = 0 THEN 'TIEN' ELSE 'PHAN_TRAM' END,
       CASE WHEN MOD(LEVEL, 2) = 0 THEN 20000 + LEVEL * 1000 ELSE 5 + MOD(LEVEL, 20) END,
       100000,
       DATE '2026-01-01',
       DATE '2026-12-31',
       1000,
       'HOAT_DONG'
FROM DUAL CONNECT BY LEVEL <= 20;

-- KHACHHANG_THANHVIEN: 1000 dong
INSERT INTO MAY2.KHACHHANG_THANHVIEN (MAKH, HANGTV, DIEMTICHLUY, NGAYDANGKY, TRANGTHAI)
SELECT
    'KH' || LPAD(LEVEL, 6, '0'),
    CASE 
        WHEN MOD(LEVEL, 4) = 0 THEN 'KIM_CUONG'
        WHEN MOD(LEVEL, 4) = 1 THEN 'VANG'
        WHEN MOD(LEVEL, 4) = 2 THEN 'BAC'
        ELSE 'DONG'
    END,
    MOD(LEVEL, 5000),
    SYSDATE - MOD(LEVEL, 365),
    'HOAT_DONG'
FROM DUAL
CONNECT BY LEVEL <= 1000;

INSERT INTO MAY2.NHANVIEN_CN02 (MANV, HOTEN, GIOITINH, SODIENTHOAI, EMAIL, CHUCVU, LUONG, MACN, TRANGTHAI)
SELECT
    'NV02' || LPAD(LEVEL, 4, '0'),
    'Nhan vien CN02 ' || LEVEL,
    CASE MOD(LEVEL, 3) WHEN 0 THEN 'NAM' WHEN 1 THEN 'NU' ELSE 'KHAC' END,
    '093' || LPAD(LEVEL, 7, '0'),
    'nvcn02_' || LEVEL || '@shop.com',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'QUAN_LY' ELSE 'NHAN_VIEN' END,
    7000000 + MOD(LEVEL, 10) * 500000,
    'CN02',
    'DANG_LAM'
FROM DUAL CONNECT BY LEVEL <= 50;

INSERT INTO MAY2.KHO_CN02_TON (MACN, MABT, SOLUONGTON, MUCTONTOITHIEU)
SELECT 'CN02', 'BT' || LPAD(LEVEL, 4, '0'), 100 + MOD(LEVEL, 200), 10
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO MAY2.KHO_CN02_BANHANG (MACN, MABT, SOLUONGDABAN, NGAYCAPNHAT)
SELECT MACN, MABT, MOD(TO_NUMBER(SUBSTR(MABT, 3)), 50), SYSDATE
FROM MAY2.KHO_CN02_TON;

INSERT INTO MAY2.DONHANG_CN02 (
    MADH, MAKH, MANV, MACN, MAVOUCHER, NGAYDAT, TRANGTHAI, DIACHINHAN,
    TONGTIENHANG, PHIVANCHUYEN, GIAMGIA, TONGTHANHTOAN
)
SELECT
    'DH02' || LPAD(LEVEL, 6, '0'),
    'KH' || LPAD(MOD(LEVEL - 1, 1000) + 1, 6, '0'),
    'NV02' || LPAD(MOD(LEVEL - 1, 50) + 1, 4, '0'),
    'CN02',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'VC' || LPAD(MOD(LEVEL - 1, 20) + 1, 3, '0') ELSE NULL END,
    SYSDATE - MOD(LEVEL, 90),
    CASE MOD(LEVEL, 5)
        WHEN 0 THEN 'HOAN_THANH'
        WHEN 1 THEN 'CHO_XAC_NHAN'
        WHEN 2 THEN 'DANG_XU_LY'
        WHEN 3 THEN 'DANG_GIAO'
        ELSE 'DA_HUY'
    END,
    'Dia chi nhan hang CN02 ' || LEVEL,
    300000 + MOD(LEVEL, 20) * 10000,
    30000,
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END
FROM DUAL
CONNECT BY LEVEL <= 250;

INSERT INTO MAY2.CT_DONHANG_CN02 (MADH, MACN, MABT, SOLUONG, DONGIA, GIAMGIA, THANHTIEN)
SELECT
    'DH02' || LPAD(ORDER_NO, 6, '0'),
    'CN02',
    'BT' || LPAD(MOD(ORDER_NO * 2 + ITEM_NO, 1000) + 1, 4, '0'),
    MOD(ORDER_NO + ITEM_NO, 3) + 1,
    100000 + ITEM_NO * 50000,
    0,
    (MOD(ORDER_NO + ITEM_NO, 3) + 1) * (100000 + ITEM_NO * 50000)
FROM (
    SELECT CEIL(LEVEL / 2) AS ORDER_NO,
           MOD(LEVEL - 1, 2) + 1 AS ITEM_NO
    FROM DUAL CONNECT BY LEVEL <= 500
);

INSERT INTO MAY2.THANHTOAN_CN02 (MATT, MADH, MACN, PHUONGTHUC, SOTIEN, NGAYTHANHTOAN, MAGIAODICH, TRANGTHAI)
SELECT
    'TT02' || LPAD(LEVEL, 6, '0'),
    'DH02' || LPAD(LEVEL, 6, '0'),
    'CN02',
    CASE MOD(LEVEL, 4) WHEN 0 THEN 'TIEN_MAT' WHEN 1 THEN 'CHUYEN_KHOAN' WHEN 2 THEN 'THE' ELSE 'VI_DIEN_TU' END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    SYSDATE - MOD(LEVEL, 90),
    'MGD02' || LPAD(LEVEL, 6, '0'),
    CASE WHEN MOD(LEVEL, 5) = 4 THEN 'CHO_THANH_TOAN' ELSE 'DA_THANH_TOAN' END
FROM DUAL
CONNECT BY LEVEL <= 250;

COMMIT;
-- =====================================================
-- PHAN QUYEN NGHIEP VU TAI MAY2 - CHI NHANH CN02
-- Schema chinh: MAY2
-- =====================================================

CREATE USER GD_MAY2 IDENTIFIED BY "123456";
CREATE USER QL_MAY2 IDENTIFIED BY "123456";
CREATE USER NV_MAY2 IDENTIFIED BY "123456";
CREATE USER KHO_MAY2 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO GD_MAY2;
GRANT CREATE SESSION TO QL_MAY2;
GRANT CREATE SESSION TO NV_MAY2;
GRANT CREATE SESSION TO KHO_MAY2;

GRANT CREATE DATABASE LINK TO GD_MAY2;

CREATE ROLE ROLE_GIAMDOC_MAY2;
CREATE ROLE ROLE_QL_MAY2;
CREATE ROLE ROLE_NV_MAY2;
CREATE ROLE ROLE_KHO_MAY2;

GRANT ROLE_GIAMDOC_MAY2 TO GD_MAY2;
GRANT ROLE_QL_MAY2 TO QL_MAY2;
GRANT ROLE_NV_MAY2 TO NV_MAY2;
GRANT ROLE_KHO_MAY2 TO KHO_MAY2;

-- Giam doc
GRANT SELECT ON MAY2.CHINHANH TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.DANHMUC TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.SANPHAM TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.BIENTHE_SANPHAM TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.VOUCHER TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.KHACHHANG_THANHVIEN TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.NHANVIEN_CN02 TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.DONHANG_CN02 TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.CT_DONHANG_CN02 TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.THANHTOAN_CN02 TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.KHO_CN02_TON TO ROLE_GIAMDOC_MAY2;
GRANT SELECT ON MAY2.KHO_CN02_BANHANG TO ROLE_GIAMDOC_MAY2;

-- Quan ly chi nhanh
GRANT SELECT, INSERT, UPDATE ON MAY2.NHANVIEN_CN02 TO ROLE_QL_MAY2;
GRANT SELECT, INSERT, UPDATE ON MAY2.DONHANG_CN02 TO ROLE_QL_MAY2;
GRANT SELECT, INSERT, UPDATE ON MAY2.CT_DONHANG_CN02 TO ROLE_QL_MAY2;
GRANT SELECT, INSERT, UPDATE ON MAY2.THANHTOAN_CN02 TO ROLE_QL_MAY2;
GRANT SELECT ON MAY2.KHACHHANG_THANHVIEN TO ROLE_QL_MAY2;
GRANT SELECT ON MAY2.SANPHAM TO ROLE_QL_MAY2;
GRANT SELECT ON MAY2.BIENTHE_SANPHAM TO ROLE_QL_MAY2;
GRANT SELECT ON MAY2.VOUCHER TO ROLE_QL_MAY2;

-- Nhan vien ban hang
GRANT SELECT ON MAY2.CHINHANH TO ROLE_NV_MAY2;
GRANT SELECT ON MAY2.DANHMUC TO ROLE_NV_MAY2;
GRANT SELECT ON MAY2.SANPHAM TO ROLE_NV_MAY2;
GRANT SELECT ON MAY2.BIENTHE_SANPHAM TO ROLE_NV_MAY2;
GRANT SELECT ON MAY2.VOUCHER TO ROLE_NV_MAY2;
GRANT SELECT ON MAY2.KHO_CN02_TON TO ROLE_NV_MAY2;
GRANT SELECT ON MAY2.KHACHHANG_THANHVIEN TO ROLE_NV_MAY2;
GRANT INSERT ON MAY2.DONHANG_CN02 TO ROLE_NV_MAY2;
GRANT INSERT ON MAY2.CT_DONHANG_CN02 TO ROLE_NV_MAY2;
GRANT INSERT ON MAY2.THANHTOAN_CN02 TO ROLE_NV_MAY2;

-- Quan ly kho
GRANT SELECT ON MAY2.SANPHAM TO ROLE_KHO_MAY2;
GRANT SELECT ON MAY2.BIENTHE_SANPHAM TO ROLE_KHO_MAY2;
GRANT SELECT, INSERT, UPDATE ON MAY2.KHO_CN02_TON TO ROLE_KHO_MAY2;
GRANT SELECT, INSERT, UPDATE ON MAY2.KHO_CN02_BANHANG TO ROLE_KHO_MAY2;
-- =====================================================
-- DATABASE LINK TAI MAY2
-- MAY2 ket noi toi MAY1, MAY3, MAY4
-- =====================================================

CREATE PUBLIC DATABASE LINK LINK_MAY2_TO_MAY1
CONNECT TO MAY1 IDENTIFIED BY "123456"
USING 'MAY1';

CREATE PUBLIC DATABASE LINK LINK_MAY2_TO_MAY3
CONNECT TO MAY3 IDENTIFIED BY "123456"
USING 'MAY3';

CREATE PUBLIC DATABASE LINK LINK_MAY2_TO_MAY4
CONNECT TO MAY4 IDENTIFIED BY "123456"
USING 'MAY4';
-- =====================================================
-- CAU TRUY VAN TAI MAY2
-- =====================================================
--Câu 4: Top 10 biến thể sản phẩm bán chạy nhất toàn hệ thống-MAY2
SELECT 
    CT.MABT,
    BT.MASP,
    BT.MAU,
    BT.KICHCO,
    COUNT(*) AS SO_LAN_XUAT_HIEN,
    SUM(CT.SOLUONG) AS TONG_SO_LUONG_BAN
FROM (
    SELECT MABT, SOLUONG
    FROM CT_DONHANG_CN01@LINK_MAY2_TO_MAY1

    UNION ALL

    SELECT MABT, SOLUONG
    FROM MAY2.CT_DONHANG_CN02

    UNION ALL

    SELECT MABT, SOLUONG
    FROM CT_DONHANG_CN03@LINK_MAY2_TO_MAY3

    UNION ALL

    SELECT MABT, SOLUONG
    FROM CT_DONHANG_CN04@LINK_MAY2_TO_MAY4
) CT
JOIN MAY2.BIENTHE_SANPHAM BT
    ON CT.MABT = BT.MABT
GROUP BY CT.MABT, BT.MASP, BT.MAU, BT.KICHCO
ORDER BY TONG_SO_LUONG_BAN DESC
FETCH FIRST 10 ROWS ONLY;
--Câu 5: Top 10 khách hàng có tổng chi tiêu cao nhất toàn hệ thống- MAY2
SELECT 
    KH.MAKH,
    KH.HOTEN,
    KH.SODIENTHOAI,
    KH.EMAIL,
    TV.HANGTV,
    TV.DIEMTICHLUY,
    COUNT(DH.MADH) AS SO_DON_DA_MUA,
    SUM(DH.TONGTHANHTOAN) AS TONG_CHI_TIEU
FROM KHACHHANG_TT@LINK_MAY2_TO_MAY1 KH
JOIN MAY2.KHACHHANG_THANHVIEN TV
    ON KH.MAKH = TV.MAKH
JOIN (
    SELECT MADH, MAKH, TONGTHANHTOAN
    FROM DONHANG_CN01@LINK_MAY2_TO_MAY1

    UNION ALL

    SELECT MADH, MAKH, TONGTHANHTOAN
    FROM MAY2.DONHANG_CN02

    UNION ALL

    SELECT MADH, MAKH, TONGTHANHTOAN
    FROM DONHANG_CN03@LINK_MAY2_TO_MAY3

    UNION ALL

    SELECT MADH, MAKH, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY2_TO_MAY4
) DH
    ON KH.MAKH = DH.MAKH
GROUP BY 
    KH.MAKH,
    KH.HOTEN,
    KH.SODIENTHOAI,
    KH.EMAIL,
    TV.HANGTV,
    TV.DIEMTICHLUY
ORDER BY TONG_CHI_TIEU DESC
FETCH FIRST 10 ROWS ONLY;
--Câu 6: Thống kê doanh thu theo phương thức thanh toán toàn hệ thống-MAY2
SELECT 
    PHUONGTHUC,
    COUNT(*) AS SO_GIAO_DICH,
    SUM(SOTIEN) AS TONG_DOANH_THU,
    ROUND(AVG(SOTIEN), 0) AS GIA_TRI_THANH_TOAN_TB
FROM (
    SELECT PHUONGTHUC, SOTIEN
    FROM THANHTOAN_CN01@LINK_MAY2_TO_MAY1

    UNION ALL

    SELECT PHUONGTHUC, SOTIEN
    FROM MAY2.THANHTOAN_CN02

    UNION ALL

    SELECT PHUONGTHUC, SOTIEN
    FROM THANHTOAN_CN03@LINK_MAY2_TO_MAY3

    UNION ALL

    SELECT PHUONGTHUC, SOTIEN
    FROM THANHTOAN_CN04@LINK_MAY2_TO_MAY4
)
GROUP BY PHUONGTHUC
ORDER BY TONG_DOANH_THU DESC
-- =====================================================
-- Function
-- =====================================================
-- Test case function
SELECT MAY1.FN_TONG_CHI_TIEU_KHACHHANG@LINK_MAY2_TO_MAY1('KH000001') AS TONG_CHI_TIEU
FROM DUAL;
-- =====================================================
-- Stored Procedure
-- =====================================================
-- Test case Stỏed Procedure
SELECT MANV, HOTEN, LUONG
FROM NHANVIEN_CN02@LINK_MAY1_TO_MAY2
WHERE MANV = 'NV020001';
--
BEGIN
    MAY1.PR_CAPNHAT_LUONG_NHANVIEN_TOANHT('NV020001', 16000000);
END;
/
--
SELECT MANV, HOTEN, LUONG
FROM NHANVIEN_CN02@LINK_MAY1_TO_MAY2
WHERE MANV = 'NV020001';
-- =====================================================
-- Trigger
-- =====================================================
-- 1) Trigger: Kiểm tra và cập nhật tông kho khi thêm chi tiết đơn hàng
CREATE OR REPLACE TRIGGER MAY2.TRG_CAPNHAT_KHO_CTDH_CN02
BEFORE INSERT ON MAY2.CT_DONHANG_CN02
FOR EACH ROW
DECLARE
    V_SOLUONGTON MAY2.KHO_CN02_TON.SOLUONGTON%TYPE;
BEGIN
    IF :NEW.MACN <> 'CN02' THEN
        RAISE_APPLICATION_ERROR(-20020, 'Chi tiet don hang CN02 chi duoc co MACN = CN02');
    END IF;

    SELECT SOLUONGTON
    INTO V_SOLUONGTON
    FROM MAY2.KHO_CN02_TON
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT
    FOR UPDATE;

    IF :NEW.SOLUONG > V_SOLUONGTON THEN
        RAISE_APPLICATION_ERROR(-20021, 'So luong ton kho CN02 khong du');
    END IF;

    UPDATE MAY2.KHO_CN02_TON
    SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

    UPDATE MAY2.KHO_CN02_BANHANG
    SET SOLUONGDABAN = SOLUONGDABAN + :NEW.SOLUONG,
        NGAYCAPNHAT = SYSDATE
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20022, 'Khong tim thay bien the san pham trong kho CN02');
END;
/
-- 2) Test case:
INSERT INTO MAY2.CT_DONHANG_CN02
VALUES ('DH02000001', 'CN01', 'BT0998', 5, 150000, 0, 750000);
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- =============================================================================
-- Dirty Read
-- =============================================================================
SELECT MACN, MABT, SOLUONGTON
FROM KHO_CN01_TON@LINK_MAY2_TO_MAY1
WHERE MACN = 'CN01'
  AND MABT = 'BT0001';
-- =============================================================================
-- Non-repeatable Read 
-- =============================================================================
UPDATE KHO_CN01_TON@LINK_MAY2_TO_MAY1
SET SOLUONGTON = 60
WHERE MACN = 'CN01'
  AND MABT = 'BT0003';

COMMIT;
-- =============================================================================
-- Phantom Read 
-- =============================================================================
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT COUNT(*) AS SO_DON_CHO_XAC_NHAN
FROM MAY2.DONHANG_CN02
WHERE TRANGTHAI = 'CHO_XAC_NHAN';
--
SELECT COUNT(*) AS SO_DON_CHO_XAC_NHAN
FROM MAY2.DONHANG_CN02
WHERE TRANGTHAI = 'CHO_XAC_NHAN';
-- Cách khắc phục
DELETE FROM MAY2.DONHANG_CN02
WHERE MADH = 'DH02TEST01';

COMMIT;
-- 
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SELECT COUNT(*) AS SO_DON_CHO_XAC_NHAN
FROM MAY2.DONHANG_CN02
WHERE TRANGTHAI = 'CHO_XAC_NHAN';
--
SELECT COUNT(*) AS SO_DON_CHO_XAC_NHAN
FROM MAY2.DONHANG_CN02
WHERE TRANGTHAI = 'CHO_XAC_NHAN';
--
ROLLBACK;
--
SELECT COUNT(*) AS SO_DON_CHO_XAC_NHAN
FROM MAY2.DONHANG_CN02
WHERE TRANGTHAI = 'CHO_XAC_NHAN';
--
DELETE FROM MAY2.DONHANG_CN02
WHERE MADH IN ('DH02TEST01', 'DH02TEST02');

COMMIT;