-- ================================================ĐÂY LÀ CHI NHÁNH 1 - MAY 1==================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- =====================================================
-- TAO USER/SCHEMA TAI MAY1 - CHI NHANH TP.HCM
-- =====================================================

CREATE USER MAY1 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO MAY1;
GRANT CREATE TABLE TO MAY1;
GRANT CREATE DATABASE LINK TO MAY1;
GRANT CREATE VIEW TO MAY1;
GRANT CREATE PROCEDURE TO MAY1;
GRANT CREATE TRIGGER TO MAY1;
GRANT CREATE SEQUENCE TO MAY1;

ALTER USER MAY1 QUOTA UNLIMITED ON USERS;
-- =====================================================
-- CREATE TABLE SITE MAY1 - CHI NHANH TP.HCM - CN01
-- Schema: MAY1
-- =====================================================

CREATE TABLE MAY1.CHINHANH (
    MACN VARCHAR2(10) PRIMARY KEY,
    TENCN VARCHAR2(100) NOT NULL,
    DIACHI VARCHAR2(200),
    SODIENTHOAI VARCHAR2(15),
    THANHPHO VARCHAR2(50) NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT CK_CN1_CHINHANH_TT CHECK (TRANGTHAI IN ('HOAT_DONG', 'TAM_NGUNG'))
);

CREATE TABLE MAY1.DANHMUC (
    MADM VARCHAR2(10) PRIMARY KEY,
    TENDM VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT CK_CN1_DANHMUC_TT CHECK (TRANGTHAI IN ('HOAT_DONG', 'TAM_NGUNG'))
);

CREATE TABLE MAY1.SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    TENSP VARCHAR2(150) NOT NULL,
    MADM VARCHAR2(10) NOT NULL,
    GIABAN NUMBER(12,0) DEFAULT 0 NOT NULL,
    MOTA VARCHAR2(500),
    NGAYTAO DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN1_SP_DM FOREIGN KEY (MADM) REFERENCES MAY1.DANHMUC(MADM),
    CONSTRAINT CK_CN1_SP_GIA CHECK (GIABAN >= 0),
    CONSTRAINT CK_CN1_SP_TT CHECK (TRANGTHAI IN ('DANG_BAN', 'NGUNG_BAN'))
);

CREATE TABLE MAY1.BIENTHE_SANPHAM (
    MABT VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20) NOT NULL,
    MAU VARCHAR2(50) NOT NULL,
    KICHCO VARCHAR2(20) NOT NULL,
    SKU VARCHAR2(50) UNIQUE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN1_BT_SP FOREIGN KEY (MASP) REFERENCES MAY1.SANPHAM(MASP),
    CONSTRAINT CK_CN1_BT_TT CHECK (TRANGTHAI IN ('DANG_BAN', 'NGUNG_BAN'))
);

CREATE TABLE MAY1.VOUCHER (
    MAVOUCHER VARCHAR2(20) PRIMARY KEY,
    TENVOUCHER VARCHAR2(100) NOT NULL,
    LOAIGIAMGIA VARCHAR2(20) NOT NULL,
    GIATRIGIAM NUMBER(12,0) DEFAULT 0 NOT NULL,
    DIEUKIENTOITHIEU NUMBER(14,0) DEFAULT 0 NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    SOLUONG NUMBER(10,0) DEFAULT 0 NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL,
    CONSTRAINT CK_CN1_VC_LOAI CHECK (LOAIGIAMGIA IN ('TIEN', 'PHAN_TRAM')),
    CONSTRAINT CK_CN1_VC_NGAY CHECK (NGAYKETTHUC >= NGAYBATDAU),
    CONSTRAINT CK_CN1_VC_SL CHECK (SOLUONG >= 0)
);

CREATE TABLE MAY1.KHACHHANG_TT (
    MAKH VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    NGAYSINH DATE,
    SODIENTHOAI VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(100) UNIQUE,
    DIACHI VARCHAR2(200),
    NGAYTAO DATE DEFAULT SYSDATE,
    CONSTRAINT CK_CN1_KH_GT CHECK (GIOITINH IN ('NAM', 'NU', 'KHAC'))
);

CREATE TABLE MAY1.NHANVIEN_CN01 (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    SODIENTHOAI VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(100) UNIQUE,
    CHUCVU VARCHAR2(50) NOT NULL,
    LUONG NUMBER(12,0) DEFAULT 0 NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN01' NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_LAM' NOT NULL,
    CONSTRAINT FK_CN1_NV_CN FOREIGN KEY (MACN) REFERENCES MAY1.CHINHANH(MACN),
    CONSTRAINT CK_CN1_NV_MACN CHECK (MACN = 'CN01'),
    CONSTRAINT CK_CN1_NV_LUONG CHECK (LUONG >= 0),
    CONSTRAINT CK_CN1_NV_GT CHECK (GIOITINH IN ('NAM', 'NU', 'KHAC'))
);

CREATE TABLE MAY1.DONHANG_CN01 (
    MADH VARCHAR2(30) PRIMARY KEY,
    MAKH VARCHAR2(20) NOT NULL,
    MANV VARCHAR2(20),
    MACN VARCHAR2(10) DEFAULT 'CN01' NOT NULL,
    MAVOUCHER VARCHAR2(20),
    NGAYDAT DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_XAC_NHAN' NOT NULL,
    DIACHINHAN VARCHAR2(200),
    TONGTIENHANG NUMBER(14,0) DEFAULT 0 NOT NULL,
    PHIVANCHUYEN NUMBER(12,0) DEFAULT 0 NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    TONGTHANHTOAN NUMBER(14,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CN1_DH_KH FOREIGN KEY (MAKH) REFERENCES MAY1.KHACHHANG_TT(MAKH),
    CONSTRAINT FK_CN1_DH_NV FOREIGN KEY (MANV) REFERENCES MAY1.NHANVIEN_CN01(MANV),
    CONSTRAINT FK_CN1_DH_CN FOREIGN KEY (MACN) REFERENCES MAY1.CHINHANH(MACN),
    CONSTRAINT FK_CN1_DH_VC FOREIGN KEY (MAVOUCHER) REFERENCES MAY1.VOUCHER(MAVOUCHER),
    CONSTRAINT CK_CN1_DH_MACN CHECK (MACN = 'CN01'),
    CONSTRAINT CK_CN1_DH_TT CHECK (TRANGTHAI IN ('CHO_XAC_NHAN', 'DANG_XU_LY', 'DANG_GIAO', 'HOAN_THANH', 'DA_HUY'))
);

CREATE TABLE MAY1.CT_DONHANG_CN01 (
    MADH VARCHAR2(30),
    MACN VARCHAR2(10) DEFAULT 'CN01' NOT NULL,
    MABT VARCHAR2(20),
    SOLUONG NUMBER(10,0) NOT NULL,
    DONGIA NUMBER(12,0) NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    THANHTIEN NUMBER(14,0) NOT NULL,
    CONSTRAINT PK_CN1_CTDH PRIMARY KEY (MADH, MABT),
    CONSTRAINT FK_CN1_CTDH_DH FOREIGN KEY (MADH) REFERENCES MAY1.DONHANG_CN01(MADH),
    CONSTRAINT FK_CN1_CTDH_BT FOREIGN KEY (MABT) REFERENCES MAY1.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN1_CTDH_MACN CHECK (MACN = 'CN01'),
    CONSTRAINT CK_CN1_CTDH_SL CHECK (SOLUONG > 0)
);

CREATE TABLE MAY1.THANHTOAN_CN01 (
    MATT VARCHAR2(30) PRIMARY KEY,
    MADH VARCHAR2(30) NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN01' NOT NULL,
    PHUONGTHUC VARCHAR2(50) NOT NULL,
    SOTIEN NUMBER(14,0) NOT NULL,
    NGAYTHANHTOAN DATE DEFAULT SYSDATE,
    MAGIAODICH VARCHAR2(100) UNIQUE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_THANH_TOAN' NOT NULL,
    CONSTRAINT FK_CN1_TT_DH FOREIGN KEY (MADH) REFERENCES MAY1.DONHANG_CN01(MADH),
    CONSTRAINT CK_CN1_TT_MACN CHECK (MACN = 'CN01'),
    CONSTRAINT CK_CN1_TT_PT CHECK (PHUONGTHUC IN ('TIEN_MAT', 'CHUYEN_KHOAN', 'THE', 'VI_DIEN_TU'))
);

CREATE TABLE MAY1.KHO_CN01_TON (
    MACN VARCHAR2(10) DEFAULT 'CN01' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGTON NUMBER(10,0) DEFAULT 0 NOT NULL,
    MUCTONTOITHIEU NUMBER(10,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CN1_KHO_TON PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN1_KHO_TON_BT FOREIGN KEY (MABT) REFERENCES MAY1.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN1_KHO_TON_MACN CHECK (MACN = 'CN01'),
    CONSTRAINT CK_CN1_KHO_TON_SL CHECK (SOLUONGTON >= 0)
);

CREATE TABLE MAY1.KHO_CN01_BANHANG (
    MACN VARCHAR2(10) DEFAULT 'CN01' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGDABAN NUMBER(10,0) DEFAULT 0 NOT NULL,
    NGAYCAPNHAT DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CN1_KHO_BH PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN1_KHO_BH_TON FOREIGN KEY (MACN, MABT) REFERENCES MAY1.KHO_CN01_TON(MACN, MABT),
    CONSTRAINT CK_CN1_KHO_BH_MACN CHECK (MACN = 'CN01'),
    CONSTRAINT CK_CN1_KHO_BH_SL CHECK (SOLUONGDABAN >= 0)
);
-- =====================================================
-- INSERT DATA SITE MAY1 - CN01 - TP.HCM
-- Schema: MAY1
-- =====================================================

-- 1. CHINHANH
INSERT INTO MAY1.CHINHANH VALUES ('CN01', 'Chi nhanh TP.HCM', 'Quan 1, TP.HCM', '0901000001', 'TP.HCM', 'HOAT_DONG');
INSERT INTO MAY1.CHINHANH VALUES ('CN02', 'Chi nhanh Ha Noi', 'Quan Hoan Kiem, Ha Noi', '0901000002', 'Ha Noi', 'HOAT_DONG');
INSERT INTO MAY1.CHINHANH VALUES ('CN03', 'Chi nhanh Da Nang', 'Quan Hai Chau, Da Nang', '0901000003', 'Da Nang', 'HOAT_DONG');
INSERT INTO MAY1.CHINHANH VALUES ('CN04', 'Chi nhanh Can Tho', 'Quan Ninh Kieu, Can Tho', '0901000004', 'Can Tho', 'HOAT_DONG');

-- 2. DANHMUC
INSERT INTO MAY1.DANHMUC VALUES ('DM01', 'Ao thun', 'Danh muc ao thun', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM02', 'Ao so mi', 'Danh muc ao so mi', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM03', 'Ao khoac', 'Danh muc ao khoac', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM04', 'Quan dai', 'Danh muc quan dai', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM05', 'Quan ngan', 'Danh muc quan ngan', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM06', 'Vay', 'Danh muc vay', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM07', 'Dam', 'Danh muc dam', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM08', 'Phu kien', 'Danh muc phu kien', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM09', 'Giay dep', 'Danh muc giay dep', 'HOAT_DONG');
INSERT INTO MAY1.DANHMUC VALUES ('DM10', 'Tui xach', 'Danh muc tui xach', 'HOAT_DONG');

-- 3. SANPHAM: 200 dong
INSERT INTO MAY1.SANPHAM (MASP, TENSP, MADM, GIABAN, MOTA, NGAYTAO, TRANGTHAI)
SELECT 
    'SP' || LPAD(LEVEL, 4, '0'),
    'San pham thoi trang ' || LEVEL,
    'DM' || LPAD(MOD(LEVEL - 1, 10) + 1, 2, '0'),
    100000 + MOD(LEVEL, 50) * 10000,
    'Mo ta san pham ' || LEVEL,
    SYSDATE,
    'DANG_BAN'
FROM DUAL
CONNECT BY LEVEL <= 200;

-- 4. BIENTHE_SANPHAM: 1000 dong
INSERT INTO MAY1.BIENTHE_SANPHAM (MABT, MASP, MAU, KICHCO, SKU, TRANGTHAI)
SELECT
    'BT' || LPAD(LEVEL, 4, '0'),
    'SP' || LPAD(MOD(LEVEL - 1, 200) + 1, 4, '0'),
    CASE MOD(LEVEL, 5)
        WHEN 0 THEN 'DEN'
        WHEN 1 THEN 'TRANG'
        WHEN 2 THEN 'DO'
        WHEN 3 THEN 'XANH'
        ELSE 'BE'
    END,
    CASE MOD(LEVEL, 5)
        WHEN 0 THEN 'S'
        WHEN 1 THEN 'M'
        WHEN 2 THEN 'L'
        WHEN 3 THEN 'XL'
        ELSE 'XXL'
    END,
    'SKU_CN01_' || LPAD(LEVEL, 4, '0'),
    'DANG_BAN'
FROM DUAL
CONNECT BY LEVEL <= 1000;

-- 5. VOUCHER: 20 dong
INSERT INTO MAY1.VOUCHER (
    MAVOUCHER, TENVOUCHER, LOAIGIAMGIA, GIATRIGIAM, DIEUKIENTOITHIEU,
    NGAYBATDAU, NGAYKETTHUC, SOLUONG, TRANGTHAI
)
SELECT
    'VC' || LPAD(LEVEL, 3, '0'),
    'Voucher giam gia ' || LEVEL,
    CASE WHEN MOD(LEVEL, 2) = 0 THEN 'TIEN' ELSE 'PHAN_TRAM' END,
    CASE WHEN MOD(LEVEL, 2) = 0 THEN 20000 + LEVEL * 1000 ELSE 5 + MOD(LEVEL, 20) END,
    100000,
    DATE '2026-01-01',
    DATE '2026-12-31',
    1000,
    'HOAT_DONG'
FROM DUAL
CONNECT BY LEVEL <= 20;

-- 6. KHACHHANG_TT: 1000 dong
INSERT INTO MAY1.KHACHHANG_TT (MAKH, HOTEN, GIOITINH, NGAYSINH, SODIENTHOAI, EMAIL, DIACHI, NGAYTAO)
SELECT
    'KH' || LPAD(LEVEL, 6, '0'),
    'Khach hang ' || LEVEL,
    CASE MOD(LEVEL, 3)
        WHEN 0 THEN 'NAM'
        WHEN 1 THEN 'NU'
        ELSE 'KHAC'
    END,
    DATE '1990-01-01' + MOD(LEVEL, 10000),
    '091' || LPAD(LEVEL, 7, '0'),
    'khachhang' || LEVEL || '@gmail.com',
    'Dia chi khach hang ' || LEVEL,
    SYSDATE
FROM DUAL
CONNECT BY LEVEL <= 1000;

-- 7. NHANVIEN_CN01: 50 dong
INSERT INTO MAY1.NHANVIEN_CN01 (MANV, HOTEN, GIOITINH, SODIENTHOAI, EMAIL, CHUCVU, LUONG, MACN, TRANGTHAI)
SELECT
    'NV01' || LPAD(LEVEL, 4, '0'),
    'Nhan vien CN01 ' || LEVEL,
    CASE MOD(LEVEL, 3)
        WHEN 0 THEN 'NAM'
        WHEN 1 THEN 'NU'
        ELSE 'KHAC'
    END,
    '092' || LPAD(LEVEL, 7, '0'),
    'nvcn01_' || LEVEL || '@shop.com',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'QUAN_LY' ELSE 'NHAN_VIEN' END,
    7000000 + MOD(LEVEL, 10) * 500000,
    'CN01',
    'DANG_LAM'
FROM DUAL
CONNECT BY LEVEL <= 50;

-- 8. KHO_CN01_TON: 1000 dong
INSERT INTO MAY1.KHO_CN01_TON (MACN, MABT, SOLUONGTON, MUCTONTOITHIEU)
SELECT
    'CN01',
    'BT' || LPAD(LEVEL, 4, '0'),
    100 + MOD(LEVEL, 200),
    10
FROM DUAL
CONNECT BY LEVEL <= 1000;

-- 9. KHO_CN01_BANHANG: 1000 dong
INSERT INTO MAY1.KHO_CN01_BANHANG (MACN, MABT, SOLUONGDABAN, NGAYCAPNHAT)
SELECT
    MACN,
    MABT,
    MOD(TO_NUMBER(SUBSTR(MABT, 3)), 50),
    SYSDATE
FROM MAY1.KHO_CN01_TON;

-- 10. DONHANG_CN01: 300 dong
INSERT INTO MAY1.DONHANG_CN01 (
    MADH, MAKH, MANV, MACN, MAVOUCHER, NGAYDAT, TRANGTHAI, DIACHINHAN,
    TONGTIENHANG, PHIVANCHUYEN, GIAMGIA, TONGTHANHTOAN
)
SELECT
    'DH01' || LPAD(LEVEL, 6, '0'),
    'KH' || LPAD(MOD(LEVEL - 1, 1000) + 1, 6, '0'),
    'NV01' || LPAD(MOD(LEVEL - 1, 50) + 1, 4, '0'),
    'CN01',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'VC' || LPAD(MOD(LEVEL - 1, 20) + 1, 3, '0') ELSE NULL END,
    SYSDATE - MOD(LEVEL, 90),
    CASE MOD(LEVEL, 5)
        WHEN 0 THEN 'HOAN_THANH'
        WHEN 1 THEN 'CHO_XAC_NHAN'
        WHEN 2 THEN 'DANG_XU_LY'
        WHEN 3 THEN 'DANG_GIAO'
        ELSE 'DA_HUY'
    END,
    'Dia chi nhan hang CN01 ' || LEVEL,
    300000 + MOD(LEVEL, 20) * 10000,
    30000,
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END
FROM DUAL
CONNECT BY LEVEL <= 300;

-- 11. CT_DONHANG_CN01: 600 dong
INSERT INTO MAY1.CT_DONHANG_CN01 (MADH, MACN, MABT, SOLUONG, DONGIA, GIAMGIA, THANHTIEN)
SELECT
    'DH01' || LPAD(ORDER_NO, 6, '0'),
    'CN01',
    'BT' || LPAD(MOD(ORDER_NO * 2 + ITEM_NO, 1000) + 1, 4, '0'),
    MOD(ORDER_NO + ITEM_NO, 3) + 1,
    100000 + ITEM_NO * 50000,
    0,
    (MOD(ORDER_NO + ITEM_NO, 3) + 1) * (100000 + ITEM_NO * 50000)
FROM (
    SELECT 
        CEIL(LEVEL / 2) AS ORDER_NO,
        MOD(LEVEL - 1, 2) + 1 AS ITEM_NO
    FROM DUAL
    CONNECT BY LEVEL <= 600
);

-- 12. THANHTOAN_CN01: 300 dong
INSERT INTO MAY1.THANHTOAN_CN01 (MATT, MADH, MACN, PHUONGTHUC, SOTIEN, NGAYTHANHTOAN, MAGIAODICH, TRANGTHAI)
SELECT
    'TT01' || LPAD(LEVEL, 6, '0'),
    'DH01' || LPAD(LEVEL, 6, '0'),
    'CN01',
    CASE MOD(LEVEL, 4)
        WHEN 0 THEN 'TIEN_MAT'
        WHEN 1 THEN 'CHUYEN_KHOAN'
        WHEN 2 THEN 'THE'
        ELSE 'VI_DIEN_TU'
    END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    SYSDATE - MOD(LEVEL, 90),
    'MGD01' || LPAD(LEVEL, 6, '0'),
    CASE WHEN MOD(LEVEL, 5) = 4 THEN 'CHO_THANH_TOAN' ELSE 'DA_THANH_TOAN' END
FROM DUAL
CONNECT BY LEVEL <= 300;

COMMIT;
-- =====================================================
-- PHAN QUYEN NGHIEP VU TAI MAY1 - CHI NHANH CN01
-- Schema chinh: MAY1
-- =====================================================

-- 1. Tao user nghiep vu
CREATE USER GD_MAY1 IDENTIFIED BY "123456";
CREATE USER QL_MAY1 IDENTIFIED BY "123456";
CREATE USER NV_MAY1 IDENTIFIED BY "123456";
CREATE USER KHO_MAY1 IDENTIFIED BY "123456";

-- 2. Cap quyen dang nhap
GRANT CREATE SESSION TO GD_MAY1;
GRANT CREATE SESSION TO QL_MAY1;
GRANT CREATE SESSION TO NV_MAY1;
GRANT CREATE SESSION TO KHO_MAY1;

-- 3. Cap quyen tao database link cho giam doc neu can truy van phan tan
GRANT CREATE DATABASE LINK TO GD_MAY1;

-- 4. Tao role
CREATE ROLE ROLE_GIAMDOC_MAY1;
CREATE ROLE ROLE_QL_MAY1;
CREATE ROLE ROLE_NV_MAY1;
CREATE ROLE ROLE_KHO_MAY1;

-- 5. Gan role cho user
GRANT ROLE_GIAMDOC_MAY1 TO GD_MAY1;
GRANT ROLE_QL_MAY1 TO QL_MAY1;
GRANT ROLE_NV_MAY1 TO NV_MAY1;
GRANT ROLE_KHO_MAY1 TO KHO_MAY1;

-- 6. Quyen cho giam doc: xem toan bo bang tai MAY1
GRANT SELECT ON MAY1.CHINHANH TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.DANHMUC TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.SANPHAM TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.BIENTHE_SANPHAM TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.VOUCHER TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.KHACHHANG_TT TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.NHANVIEN_CN01 TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.DONHANG_CN01 TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.CT_DONHANG_CN01 TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.THANHTOAN_CN01 TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.KHO_CN01_TON TO ROLE_GIAMDOC_MAY1;
GRANT SELECT ON MAY1.KHO_CN01_BANHANG TO ROLE_GIAMDOC_MAY1;

-- 7. Quyen cho quan ly chi nhanh
GRANT SELECT, INSERT, UPDATE ON MAY1.NHANVIEN_CN01 TO ROLE_QL_MAY1;
GRANT SELECT, INSERT, UPDATE ON MAY1.DONHANG_CN01 TO ROLE_QL_MAY1;
GRANT SELECT, INSERT, UPDATE ON MAY1.CT_DONHANG_CN01 TO ROLE_QL_MAY1;
GRANT SELECT, INSERT, UPDATE ON MAY1.THANHTOAN_CN01 TO ROLE_QL_MAY1;
GRANT SELECT ON MAY1.KHACHHANG_TT TO ROLE_QL_MAY1;
GRANT SELECT ON MAY1.SANPHAM TO ROLE_QL_MAY1;
GRANT SELECT ON MAY1.BIENTHE_SANPHAM TO ROLE_QL_MAY1;
GRANT SELECT ON MAY1.VOUCHER TO ROLE_QL_MAY1;

-- 8. Quyen cho nhan vien ban hang
GRANT SELECT ON MAY1.CHINHANH TO ROLE_NV_MAY1;
GRANT SELECT ON MAY1.DANHMUC TO ROLE_NV_MAY1;
GRANT SELECT ON MAY1.SANPHAM TO ROLE_NV_MAY1;
GRANT SELECT ON MAY1.BIENTHE_SANPHAM TO ROLE_NV_MAY1;
GRANT SELECT ON MAY1.VOUCHER TO ROLE_NV_MAY1;
GRANT SELECT ON MAY1.KHO_CN01_TON TO ROLE_NV_MAY1;
GRANT SELECT ON MAY1.KHACHHANG_TT TO ROLE_NV_MAY1;
GRANT INSERT ON MAY1.DONHANG_CN01 TO ROLE_NV_MAY1;
GRANT INSERT ON MAY1.CT_DONHANG_CN01 TO ROLE_NV_MAY1;
GRANT INSERT ON MAY1.THANHTOAN_CN01 TO ROLE_NV_MAY1;

-- 9. Quyen cho quan ly kho
GRANT SELECT ON MAY1.SANPHAM TO ROLE_KHO_MAY1;
GRANT SELECT ON MAY1.BIENTHE_SANPHAM TO ROLE_KHO_MAY1;
GRANT SELECT, INSERT, UPDATE ON MAY1.KHO_CN01_TON TO ROLE_KHO_MAY1;
GRANT SELECT, INSERT, UPDATE ON MAY1.KHO_CN01_BANHANG TO ROLE_KHO_MAY1;
-- =====================================================
-- DATABASE LINK TAI MAY1
-- MAY1 ket noi toi MAY2, MAY3, MAY4
-- =====================================================

CREATE PUBLIC DATABASE LINK LINK_MAY1_TO_MAY2
CONNECT TO MAY2 IDENTIFIED BY "123456"
USING 'MAY2';

CREATE PUBLIC DATABASE LINK LINK_MAY1_TO_MAY3
CONNECT TO MAY3 IDENTIFIED BY "123456"
USING 'MAY3';

CREATE PUBLIC DATABASE LINK LINK_MAY1_TO_MAY4
CONNECT TO MAY4 IDENTIFIED BY "123456"
USING 'MAY4';
-- =====================================================
-- CAU TRUY VAN TAI MAY1
-- =====================================================
--Câu 1: Thống kê tổng quan đơn hàng theo từng chi nhánh- MAY1
SELECT 
    MACN,
    COUNT(*) AS SO_DON_HANG,
    SUM(TONGTHANHTOAN) AS TONG_DOANH_THU,
    ROUND(AVG(TONGTHANHTOAN), 0) AS GIA_TRI_DON_TRUNG_BINH
FROM (
    SELECT MACN, TONGTHANHTOAN
    FROM MAY1.DONHANG_CN01

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN02@LINK_MAY1_TO_MAY2

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN03@LINK_MAY1_TO_MAY3

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY1_TO_MAY4
)
GROUP BY MACN
ORDER BY MACN

--Câu 2: Thống kê doanh thu theo trạng thái đơn hàng toàn hệ thống-MAY1
SELECT 
    TRANGTHAI,
    COUNT(*) AS SO_DON_HANG,
    SUM(TONGTHANHTOAN) AS TONG_GIA_TRI_DON,
    ROUND(AVG(TONGTHANHTOAN), 0) AS GIA_TRI_TRUNG_BINH
FROM (
    SELECT TRANGTHAI, TONGTHANHTOAN
    FROM MAY1.DONHANG_CN01

    UNION ALL

    SELECT TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN02@LINK_MAY1_TO_MAY2

    UNION ALL

    SELECT TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN03@LINK_MAY1_TO_MAY3

    UNION ALL

    SELECT TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY1_TO_MAY4
)
GROUP BY TRANGTHAI
ORDER BY SO_DON_HANG DESC

--Câu 3: Tìm các chi nhánh có tổng doanh thu thanh toán lớn hơn 80 triệu-MAY1
SELECT 
    MACN,
    SUM(SOTIEN) AS TONG_DOANH_THU_THANH_TOAN
FROM (
    SELECT MACN, SOTIEN
    FROM MAY1.THANHTOAN_CN01

    UNION ALL

    SELECT MACN, SOTIEN
    FROM THANHTOAN_CN02@LINK_MAY1_TO_MAY2

    UNION ALL

    SELECT MACN, SOTIEN
    FROM THANHTOAN_CN03@LINK_MAY1_TO_MAY3

    UNION ALL

    SELECT MACN, SOTIEN
    FROM THANHTOAN_CN04@LINK_MAY1_TO_MAY4
)
GROUP BY MACN
HAVING SUM(SOTIEN) > 80000000
ORDER BY TONG_DOANH_THU_THANH_TOAN DESC
-- =====================================================
-- Function
-- =====================================================
-- 1) Function: Tính tổng chi tiêu khách hàng toàn hệ thống
CREATE OR REPLACE FUNCTION MAY1.FN_TONG_CHI_TIEU_KHACHHANG (
    P_MAKH IN VARCHAR2
)
RETURN NUMBER
IS
    V_TONG_CN01 NUMBER := 0;
    V_TONG_CN02 NUMBER := 0;
    V_TONG_CN03 NUMBER := 0;
    V_TONG_CN04 NUMBER := 0;
    V_TONG_TOAN_HE_THONG NUMBER := 0;
BEGIN
    -- 1. Tinh tong chi tieu tai chi nhanh CN01 - MAY1
    SELECT NVL(SUM(TONGTHANHTOAN), 0)
    INTO V_TONG_CN01
    FROM MAY1.DONHANG_CN01
    WHERE MAKH = P_MAKH;

    -- 2. Tinh tong chi tieu tai chi nhanh CN02 - MAY2
    SELECT NVL(SUM(TONGTHANHTOAN), 0)
    INTO V_TONG_CN02
    FROM DONHANG_CN02@LINK_MAY1_TO_MAY2
    WHERE MAKH = P_MAKH;

    -- 3. Tinh tong chi tieu tai chi nhanh CN03 - MAY3
    SELECT NVL(SUM(TONGTHANHTOAN), 0)
    INTO V_TONG_CN03
    FROM DONHANG_CN03@LINK_MAY1_TO_MAY3
    WHERE MAKH = P_MAKH;

    -- 4. Tinh tong chi tieu tai chi nhanh CN04 - MAY4
    SELECT NVL(SUM(TONGTHANHTOAN), 0)
    INTO V_TONG_CN04
    FROM DONHANG_CN04@LINK_MAY1_TO_MAY4
    WHERE MAKH = P_MAKH;

    -- 5. Cong tong chi tieu toan he thong
    V_TONG_TOAN_HE_THONG := V_TONG_CN01 + V_TONG_CN02 + V_TONG_CN03 + V_TONG_CN04;

    RETURN V_TONG_TOAN_HE_THONG;

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Loi khi tinh tong chi tieu khach hang tren he thong phan tan: ' || SQLERRM
        );
END;
/
-- Test case function
SELECT MAY1.FN_TONG_CHI_TIEU_KHACHHANG('KH000001') AS TONG_CHI_TIEU
FROM DUAL;
-- =====================================================
-- Stored Procedure
-- =====================================================
-- 1. Stored Procedure: Cập nhật lương nhân viên trên toàn hệ thống

CREATE OR REPLACE PROCEDURE MAY1.PR_CAPNHAT_LUONG_NHANVIEN_TOANHT (
    P_MANV      IN VARCHAR2,
    P_LUONG_MOI IN NUMBER
)
IS
    V_COUNT NUMBER := 0;
    V_LUONG_CU NUMBER := 0;
BEGIN
    -- 1. Kiem tra luong moi hop le
    IF P_LUONG_MOI <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Luong moi phai lon hon 0');
    END IF;

    -- 2. Tim nhan vien tai MAY1 - CN01
    SELECT COUNT(*)
    INTO V_COUNT
    FROM MAY1.NHANVIEN_CN01
    WHERE MANV = P_MANV;

    IF V_COUNT > 0 THEN
        SELECT LUONG
        INTO V_LUONG_CU
        FROM MAY1.NHANVIEN_CN01
        WHERE MANV = P_MANV;

        IF P_LUONG_MOI <= V_LUONG_CU THEN
            RAISE_APPLICATION_ERROR(-20002, 'Luong moi phai lon hon luong hien tai');
        END IF;

        UPDATE MAY1.NHANVIEN_CN01
        SET LUONG = P_LUONG_MOI
        WHERE MANV = P_MANV;

        COMMIT;
        RETURN;
    END IF;

    -- 3. Tim nhan vien tai MAY2 - CN02
    SELECT COUNT(*)
    INTO V_COUNT
    FROM NHANVIEN_CN02@LINK_MAY1_TO_MAY2
    WHERE MANV = P_MANV;

    IF V_COUNT > 0 THEN
        SELECT LUONG
        INTO V_LUONG_CU
        FROM NHANVIEN_CN02@LINK_MAY1_TO_MAY2
        WHERE MANV = P_MANV;

        IF P_LUONG_MOI <= V_LUONG_CU THEN
            RAISE_APPLICATION_ERROR(-20002, 'Luong moi phai lon hon luong hien tai');
        END IF;

        UPDATE NHANVIEN_CN02@LINK_MAY1_TO_MAY2
        SET LUONG = P_LUONG_MOI
        WHERE MANV = P_MANV;

        COMMIT;
        RETURN;
    END IF;

    -- 4. Tim nhan vien tai MAY3 - CN03
    SELECT COUNT(*)
    INTO V_COUNT
    FROM NHANVIEN_CN03@LINK_MAY1_TO_MAY3
    WHERE MANV = P_MANV;

    IF V_COUNT > 0 THEN
        SELECT LUONG
        INTO V_LUONG_CU
        FROM NHANVIEN_CN03@LINK_MAY1_TO_MAY3
        WHERE MANV = P_MANV;

        IF P_LUONG_MOI <= V_LUONG_CU THEN
            RAISE_APPLICATION_ERROR(-20002, 'Luong moi phai lon hon luong hien tai');
        END IF;

        UPDATE NHANVIEN_CN03@LINK_MAY1_TO_MAY3
        SET LUONG = P_LUONG_MOI
        WHERE MANV = P_MANV;

        COMMIT;
        RETURN;
    END IF;

    -- 5. Tim nhan vien tai MAY4 - CN04
    SELECT COUNT(*)
    INTO V_COUNT
    FROM NHANVIEN_CN04@LINK_MAY1_TO_MAY4
    WHERE MANV = P_MANV;

    IF V_COUNT > 0 THEN
        SELECT LUONG
        INTO V_LUONG_CU
        FROM NHANVIEN_CN04@LINK_MAY1_TO_MAY4
        WHERE MANV = P_MANV;

        IF P_LUONG_MOI <= V_LUONG_CU THEN
            RAISE_APPLICATION_ERROR(-20002, 'Luong moi phai lon hon luong hien tai');
        END IF;

        UPDATE NHANVIEN_CN04@LINK_MAY1_TO_MAY4
        SET LUONG = P_LUONG_MOI
        WHERE MANV = P_MANV;

        COMMIT;
        RETURN;
    END IF;

    -- 6. Neu khong tim thay nhan vien trong 4 site
    RAISE_APPLICATION_ERROR(-20003, 'Khong tim thay nhan vien trong toan he thong');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(
            -20004,
            'Loi khi cap nhat luong nhan vien tren he thong phan tan: ' || SQLERRM
        );
END;
/
-- Thực thi/ kiểm thử Procedure:
SELECT MANV, HOTEN, LUONG
FROM MAY1.NHANVIEN_CN01
WHERE MANV = 'NV010001';
--
BEGIN
    MAY1.PR_CAPNHAT_LUONG_NHANVIEN_TOANHT('NV010001', 15000000);
END;
/
--
SELECT MANV, HOTEN, LUONG
FROM MAY1.NHANVIEN_CN01
WHERE MANV = 'NV010001';
-- =====================================================
-- Trigger
-- =====================================================
-- 1) Trigger: Kiểm tra và cập nhật tông kho khi thêm chi tiết đơn hàng
CREATE OR REPLACE TRIGGER MAY1.TRG_CAPNHAT_KHO_CTDH_CN01
BEFORE INSERT ON MAY1.CT_DONHANG_CN01
FOR EACH ROW
DECLARE
    V_SOLUONGTON MAY1.KHO_CN01_TON.SOLUONGTON%TYPE;
BEGIN
    IF :NEW.MACN <> 'CN01' THEN
        RAISE_APPLICATION_ERROR(-20010, 'Chi tiet don hang CN01 chi duoc co MACN = CN01');
    END IF;

    SELECT SOLUONGTON
    INTO V_SOLUONGTON
    FROM MAY1.KHO_CN01_TON
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT
    FOR UPDATE;

    IF :NEW.SOLUONG > V_SOLUONGTON THEN
        RAISE_APPLICATION_ERROR(-20011, 'So luong ton kho CN01 khong du');
    END IF;

    UPDATE MAY1.KHO_CN01_TON
    SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

    UPDATE MAY1.KHO_CN01_BANHANG
    SET SOLUONGDABAN = SOLUONGDABAN + :NEW.SOLUONG,
        NGAYCAPNHAT = SYSDATE
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20012, 'Khong tim thay bien the san pham trong kho CN01');
END;
/
-- 2) Test case:
SELECT 
    TON.MACN,
    TON.MABT,
    TON.SOLUONGTON,
    BH.SOLUONGDABAN
FROM MAY1.KHO_CN01_TON TON
JOIN MAY1.KHO_CN01_BANHANG BH
    ON TON.MACN = BH.MACN
   AND TON.MABT = BH.MABT
WHERE TON.MACN = 'CN01'
  AND TON.MABT = 'BT0999';
--
INSERT INTO MAY1.CT_DONHANG_CN01
VALUES ('DH01000001', 'CN01', 'BT0999', 5, 150000, 0, 750000);
--
SELECT 
    TON.MACN,
    TON.MABT,
    TON.SOLUONGTON,
    BH.SOLUONGDABAN
FROM MAY1.KHO_CN01_TON TON
JOIN MAY1.KHO_CN01_BANHANG BH
    ON TON.MACN = BH.MACN
   AND TON.MABT = BH.MABT
WHERE TON.MACN = 'CN01'
  AND TON.MABT = 'BT0999';
-- =============================================================================
-- Dirty Read
-- =============================================================================
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT MACN, MABT, SOLUONGTON
FROM MAY1.KHO_CN01_TON
WHERE MACN = 'CN01'
  AND MABT = 'BT0001';
--
UPDATE MAY1.KHO_CN01_TON
SET SOLUONGTON = 50
WHERE MACN = 'CN01'
  AND MABT = 'BT0001';
--
SELECT MACN, MABT, SOLUONGTON
FROM MAY1.KHO_CN01_TON
WHERE MACN = 'CN01'
  AND MABT = 'BT0001';
--
ROLLBACK;
-- 
SELECT MACN, MABT, SOLUONGTON
FROM MAY1.KHO_CN01_TON
WHERE MACN = 'CN01'
  AND MABT = 'BT0001';
-- =============================================================================
-- Non-repeatable Read 
-- ============================================================================= 
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT MACN, MABT, SOLUONGTON
FROM MAY1.KHO_CN01_TON
WHERE MACN = 'CN01'
  AND MABT = 'BT0003';
--
SELECT MACN, MABT, SOLUONGTON
FROM MAY1.KHO_CN01_TON
WHERE MACN = 'CN01'
  AND MABT = 'BT0003';
-- =============================================================================
-- Tối ưu truy vấn
-- =============================================================================
-- Câu chưa tối ưu:
SELECT MACN, COUNT(*) AS SO_DON, SUM(TONGTHANHTOAN) AS DOANH_THU
FROM (
    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM MAY1.DONHANG_CN01

    UNION ALL

    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN02@LINK_MAY1_TO_MAY2

    UNION ALL

    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN03@LINK_MAY1_TO_MAY3

    UNION ALL

    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY1_TO_MAY4
)
WHERE TRANGTHAI = 'HOAN_THANH'
GROUP BY MACN
ORDER BY MACN;
-- Câu đã tối ưu:
SELECT MACN, COUNT(*) AS SO_DON, SUM(TONGTHANHTOAN) AS DOANH_THU
FROM (
    SELECT MACN, TONGTHANHTOAN
    FROM MAY1.DONHANG_CN01
    WHERE TRANGTHAI = 'HOAN_THANH'

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN02@LINK_MAY1_TO_MAY2
    WHERE TRANGTHAI = 'HOAN_THANH'

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN03@LINK_MAY1_TO_MAY3
    WHERE TRANGTHAI = 'HOAN_THANH'

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY1_TO_MAY4
    WHERE TRANGTHAI = 'HOAN_THANH'
)
GROUP BY MACN
ORDER BY MACN;