-- ================================================ĐÂY LÀ CHI NHÁNH 4 - MAY 4==================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- =====================================================
-- TAO USER/SCHEMA TAI MAY4 - TRUNG TAM QUAN LY
-- =====================================================

CREATE USER MAY4 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO MAY4;
GRANT CREATE TABLE TO MAY4;
GRANT CREATE DATABASE LINK TO MAY4;
GRANT CREATE VIEW TO MAY4;
GRANT CREATE PROCEDURE TO MAY4;
GRANT CREATE TRIGGER TO MAY4;
GRANT CREATE SEQUENCE TO MAY4;

ALTER USER MAY4 QUOTA UNLIMITED ON USERS;
-- =====================================================
-- CREATE TABLE SITE MAY4 - CHI NHANH CAN THO - CN04
-- Schema: MAY4
-- =====================================================

CREATE TABLE MAY4.CHINHANH (
    MACN VARCHAR2(10) PRIMARY KEY,
    TENCN VARCHAR2(100) NOT NULL,
    DIACHI VARCHAR2(200),
    SODIENTHOAI VARCHAR2(15),
    THANHPHO VARCHAR2(50) NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY4.DANHMUC (
    MADM VARCHAR2(10) PRIMARY KEY,
    TENDM VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY4.SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    TENSP VARCHAR2(150) NOT NULL,
    MADM VARCHAR2(10) NOT NULL,
    GIABAN NUMBER(12,0) DEFAULT 0 NOT NULL,
    MOTA VARCHAR2(500),
    NGAYTAO DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN4_SP_DM FOREIGN KEY (MADM) REFERENCES MAY4.DANHMUC(MADM)
);

CREATE TABLE MAY4.BIENTHE_SANPHAM (
    MABT VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20) NOT NULL,
    MAU VARCHAR2(50) NOT NULL,
    KICHCO VARCHAR2(20) NOT NULL,
    SKU VARCHAR2(50) UNIQUE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN4_BT_SP FOREIGN KEY (MASP) REFERENCES MAY4.SANPHAM(MASP)
);

CREATE TABLE MAY4.VOUCHER (
    MAVOUCHER VARCHAR2(20) PRIMARY KEY,
    TENVOUCHER VARCHAR2(100) NOT NULL,
    LOAIGIAMGIA VARCHAR2(20) NOT NULL,
    GIATRIGIAM NUMBER(12,0) DEFAULT 0 NOT NULL,
    DIEUKIENTOITHIEU NUMBER(14,0) DEFAULT 0 NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    SOLUONG NUMBER(10,0) DEFAULT 0 NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY4.NHANVIEN_CN04 (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    SODIENTHOAI VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(100) UNIQUE,
    CHUCVU VARCHAR2(50) NOT NULL,
    LUONG NUMBER(12,0) DEFAULT 0 NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN04' NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_LAM' NOT NULL,
    CONSTRAINT FK_CN4_NV_CN FOREIGN KEY (MACN) REFERENCES MAY4.CHINHANH(MACN),
    CONSTRAINT CK_CN4_NV_MACN CHECK (MACN = 'CN04')
);

CREATE TABLE MAY4.DONHANG_CN04 (
    MADH VARCHAR2(30) PRIMARY KEY,
    MAKH VARCHAR2(20) NOT NULL,
    MANV VARCHAR2(20),
    MACN VARCHAR2(10) DEFAULT 'CN04' NOT NULL,
    MAVOUCHER VARCHAR2(20),
    NGAYDAT DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_XAC_NHAN' NOT NULL,
    DIACHINHAN VARCHAR2(200),
    TONGTIENHANG NUMBER(14,0) DEFAULT 0 NOT NULL,
    PHIVANCHUYEN NUMBER(12,0) DEFAULT 0 NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    TONGTHANHTOAN NUMBER(14,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CN4_DH_NV FOREIGN KEY (MANV) REFERENCES MAY4.NHANVIEN_CN04(MANV),
    CONSTRAINT FK_CN4_DH_CN FOREIGN KEY (MACN) REFERENCES MAY4.CHINHANH(MACN),
    CONSTRAINT FK_CN4_DH_VC FOREIGN KEY (MAVOUCHER) REFERENCES MAY4.VOUCHER(MAVOUCHER),
    CONSTRAINT CK_CN4_DH_MACN CHECK (MACN = 'CN04'),
    CONSTRAINT CK_CN4_DH_TT CHECK (TRANGTHAI IN ('CHO_XAC_NHAN', 'DANG_XU_LY', 'DANG_GIAO', 'HOAN_THANH', 'DA_HUY'))
);

CREATE TABLE MAY4.CT_DONHANG_CN04 (
    MADH VARCHAR2(30),
    MACN VARCHAR2(10) DEFAULT 'CN04' NOT NULL,
    MABT VARCHAR2(20),
    SOLUONG NUMBER(10,0) NOT NULL,
    DONGIA NUMBER(12,0) NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    THANHTIEN NUMBER(14,0) NOT NULL,
    CONSTRAINT PK_CN4_CTDH PRIMARY KEY (MADH, MABT),
    CONSTRAINT FK_CN4_CTDH_DH FOREIGN KEY (MADH) REFERENCES MAY4.DONHANG_CN04(MADH),
    CONSTRAINT FK_CN4_CTDH_BT FOREIGN KEY (MABT) REFERENCES MAY4.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN4_CTDH_MACN CHECK (MACN = 'CN04'),
    CONSTRAINT CK_CN4_CTDH_SL CHECK (SOLUONG > 0)
);

CREATE TABLE MAY4.THANHTOAN_CN04 (
    MATT VARCHAR2(30) PRIMARY KEY,
    MADH VARCHAR2(30) NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN04' NOT NULL,
    PHUONGTHUC VARCHAR2(50) NOT NULL,
    SOTIEN NUMBER(14,0) NOT NULL,
    NGAYTHANHTOAN DATE DEFAULT SYSDATE,
    MAGIAODICH VARCHAR2(100) UNIQUE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_THANH_TOAN' NOT NULL,
    CONSTRAINT FK_CN4_TT_DH FOREIGN KEY (MADH) REFERENCES MAY4.DONHANG_CN04(MADH),
    CONSTRAINT CK_CN4_TT_MACN CHECK (MACN = 'CN04')
);

CREATE TABLE MAY4.KHO_CN04_TON (
    MACN VARCHAR2(10) DEFAULT 'CN04' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGTON NUMBER(10,0) DEFAULT 0 NOT NULL,
    MUCTONTOITHIEU NUMBER(10,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CN4_KHO_TON PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN4_KHO_TON_BT FOREIGN KEY (MABT) REFERENCES MAY4.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN4_KHO_TON_MACN CHECK (MACN = 'CN04')
);

CREATE TABLE MAY4.KHO_CN04_BANHANG (
    MACN VARCHAR2(10) DEFAULT 'CN04' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGDABAN NUMBER(10,0) DEFAULT 0 NOT NULL,
    NGAYCAPNHAT DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CN4_KHO_BH PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN4_KHO_BH_TON FOREIGN KEY (MACN, MABT) REFERENCES MAY4.KHO_CN04_TON(MACN, MABT),
    CONSTRAINT CK_CN4_KHO_BH_MACN CHECK (MACN = 'CN04')
);
-- =====================================================
-- INSERT DATA SITE MAY4 - CN04 - CAN THO
-- Schema: MAY4
-- =====================================================

INSERT INTO MAY4.CHINHANH VALUES ('CN01', 'Chi nhanh TP.HCM', 'Quan 1, TP.HCM', '0901000001', 'TP.HCM', 'HOAT_DONG');
INSERT INTO MAY4.CHINHANH VALUES ('CN02', 'Chi nhanh Ha Noi', 'Quan Hoan Kiem, Ha Noi', '0901000002', 'Ha Noi', 'HOAT_DONG');
INSERT INTO MAY4.CHINHANH VALUES ('CN03', 'Chi nhanh Da Nang', 'Quan Hai Chau, Da Nang', '0901000003', 'Da Nang', 'HOAT_DONG');
INSERT INTO MAY4.CHINHANH VALUES ('CN04', 'Chi nhanh Can Tho', 'Quan Ninh Kieu, Can Tho', '0901000004', 'Can Tho', 'HOAT_DONG');

INSERT INTO MAY4.DANHMUC VALUES ('DM01', 'Ao thun', 'Danh muc ao thun', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM02', 'Ao so mi', 'Danh muc ao so mi', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM03', 'Ao khoac', 'Danh muc ao khoac', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM04', 'Quan dai', 'Danh muc quan dai', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM05', 'Quan ngan', 'Danh muc quan ngan', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM06', 'Vay', 'Danh muc vay', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM07', 'Dam', 'Danh muc dam', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM08', 'Phu kien', 'Danh muc phu kien', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM09', 'Giay dep', 'Danh muc giay dep', 'HOAT_DONG');
INSERT INTO MAY4.DANHMUC VALUES ('DM10', 'Tui xach', 'Danh muc tui xach', 'HOAT_DONG');

INSERT INTO MAY4.SANPHAM (MASP, TENSP, MADM, GIABAN, MOTA, NGAYTAO, TRANGTHAI)
SELECT 'SP' || LPAD(LEVEL, 4, '0'),
       'San pham thoi trang ' || LEVEL,
       'DM' || LPAD(MOD(LEVEL - 1, 10) + 1, 2, '0'),
       100000 + MOD(LEVEL, 50) * 10000,
       'Mo ta san pham ' || LEVEL,
       SYSDATE,
       'DANG_BAN'
FROM DUAL CONNECT BY LEVEL <= 200;

INSERT INTO MAY4.BIENTHE_SANPHAM (MABT, MASP, MAU, KICHCO, SKU, TRANGTHAI)
SELECT 'BT' || LPAD(LEVEL, 4, '0'),
       'SP' || LPAD(MOD(LEVEL - 1, 200) + 1, 4, '0'),
       CASE MOD(LEVEL, 5) WHEN 0 THEN 'DEN' WHEN 1 THEN 'TRANG' WHEN 2 THEN 'DO' WHEN 3 THEN 'XANH' ELSE 'BE' END,
       CASE MOD(LEVEL, 5) WHEN 0 THEN 'S' WHEN 1 THEN 'M' WHEN 2 THEN 'L' WHEN 3 THEN 'XL' ELSE 'XXL' END,
       'SKU_CN04_' || LPAD(LEVEL, 4, '0'),
       'DANG_BAN'
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO MAY4.VOUCHER (
    MAVOUCHER, TENVOUCHER, LOAIGIAMGIA, GIATRIGIAM, DIEUKIENTOITHIEU,
    NGAYBATDAU, NGAYKETTHUC, SOLUONG, TRANGTHAI
)
SELECT 'VC' || LPAD(LEVEL, 3, '0'),
       'Voucher giam gia ' || LEVEL,
       CASE WHEN MOD(LEVEL, 2) = 0 THEN 'TIEN' ELSE 'PHAN_TRAM' END,
       CASE WHEN MOD(LEVEL, 2) = 0 THEN 20000 + LEVEL * 1000 ELSE 5 + MOD(LEVEL, 20) END,
       100000,
       DATE '2026-01-01',
       DATE '2026-12-31',
       1000,
       'HOAT_DONG'
FROM DUAL CONNECT BY LEVEL <= 20;

INSERT INTO MAY4.NHANVIEN_CN04 (MANV, HOTEN, GIOITINH, SODIENTHOAI, EMAIL, CHUCVU, LUONG, MACN, TRANGTHAI)
SELECT
    'NV04' || LPAD(LEVEL, 4, '0'),
    'Nhan vien CN04 ' || LEVEL,
    CASE MOD(LEVEL, 3) WHEN 0 THEN 'NAM' WHEN 1 THEN 'NU' ELSE 'KHAC' END,
    '095' || LPAD(LEVEL, 7, '0'),
    'nvcn04_' || LEVEL || '@shop.com',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'QUAN_LY' ELSE 'NHAN_VIEN' END,
    7000000 + MOD(LEVEL, 10) * 500000,
    'CN04',
    'DANG_LAM'
FROM DUAL CONNECT BY LEVEL <= 50;

INSERT INTO MAY4.KHO_CN04_TON (MACN, MABT, SOLUONGTON, MUCTONTOITHIEU)
SELECT 'CN04', 'BT' || LPAD(LEVEL, 4, '0'), 100 + MOD(LEVEL, 200), 10
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO MAY4.KHO_CN04_BANHANG (MACN, MABT, SOLUONGDABAN, NGAYCAPNHAT)
SELECT MACN, MABT, MOD(TO_NUMBER(SUBSTR(MABT, 3)), 50), SYSDATE
FROM MAY4.KHO_CN04_TON;

INSERT INTO MAY4.DONHANG_CN04 (
    MADH, MAKH, MANV, MACN, MAVOUCHER, NGAYDAT, TRANGTHAI, DIACHINHAN,
    TONGTIENHANG, PHIVANCHUYEN, GIAMGIA, TONGTHANHTOAN
)
SELECT
    'DH04' || LPAD(LEVEL, 6, '0'),
    'KH' || LPAD(MOD(LEVEL - 1, 1000) + 1, 6, '0'),
    'NV04' || LPAD(MOD(LEVEL - 1, 50) + 1, 4, '0'),
    'CN04',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'VC' || LPAD(MOD(LEVEL - 1, 20) + 1, 3, '0') ELSE NULL END,
    SYSDATE - MOD(LEVEL, 90),
    CASE MOD(LEVEL, 5)
        WHEN 0 THEN 'HOAN_THANH'
        WHEN 1 THEN 'CHO_XAC_NHAN'
        WHEN 2 THEN 'DANG_XU_LY'
        WHEN 3 THEN 'DANG_GIAO'
        ELSE 'DA_HUY'
    END,
    'Dia chi nhan hang CN04 ' || LEVEL,
    300000 + MOD(LEVEL, 20) * 10000,
    30000,
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END
FROM DUAL
CONNECT BY LEVEL <= 200;

INSERT INTO MAY4.CT_DONHANG_CN04 (MADH, MACN, MABT, SOLUONG, DONGIA, GIAMGIA, THANHTIEN)
SELECT
    'DH04' || LPAD(ORDER_NO, 6, '0'),
    'CN04',
    'BT' || LPAD(MOD(ORDER_NO * 2 + ITEM_NO, 1000) + 1, 4, '0'),
    MOD(ORDER_NO + ITEM_NO, 3) + 1,
    100000 + ITEM_NO * 50000,
    0,
    (MOD(ORDER_NO + ITEM_NO, 3) + 1) * (100000 + ITEM_NO * 50000)
FROM (
    SELECT CEIL(LEVEL / 2) AS ORDER_NO,
           MOD(LEVEL - 1, 2) + 1 AS ITEM_NO
    FROM DUAL CONNECT BY LEVEL <= 400
);

INSERT INTO MAY4.THANHTOAN_CN04 (MATT, MADH, MACN, PHUONGTHUC, SOTIEN, NGAYTHANHTOAN, MAGIAODICH, TRANGTHAI)
SELECT
    'TT04' || LPAD(LEVEL, 6, '0'),
    'DH04' || LPAD(LEVEL, 6, '0'),
    'CN04',
    CASE MOD(LEVEL, 4) WHEN 0 THEN 'TIEN_MAT' WHEN 1 THEN 'CHUYEN_KHOAN' WHEN 2 THEN 'THE' ELSE 'VI_DIEN_TU' END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    SYSDATE - MOD(LEVEL, 90),
    'MGD04' || LPAD(LEVEL, 6, '0'),
    CASE WHEN MOD(LEVEL, 5) = 4 THEN 'CHO_THANH_TOAN' ELSE 'DA_THANH_TOAN' END
FROM DUAL
CONNECT BY LEVEL <= 200;

COMMIT;
-- =====================================================
-- PHAN QUYEN NGHIEP VU TAI MAY4 - CHI NHANH CN04
-- Schema chinh: MAY4
-- =====================================================

CREATE USER GD_MAY4 IDENTIFIED BY "123456";
CREATE USER QL_MAY4 IDENTIFIED BY "123456";
CREATE USER NV_MAY4 IDENTIFIED BY "123456";
CREATE USER KHO_MAY4 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO GD_MAY4;
GRANT CREATE SESSION TO QL_MAY4;
GRANT CREATE SESSION TO NV_MAY4;
GRANT CREATE SESSION TO KHO_MAY4;

GRANT CREATE DATABASE LINK TO GD_MAY4;

CREATE ROLE ROLE_GIAMDOC_MAY4;
CREATE ROLE ROLE_QL_MAY4;
CREATE ROLE ROLE_NV_MAY4;
CREATE ROLE ROLE_KHO_MAY4;

GRANT ROLE_GIAMDOC_MAY4 TO GD_MAY4;
GRANT ROLE_QL_MAY4 TO QL_MAY4;
GRANT ROLE_NV_MAY4 TO NV_MAY4;
GRANT ROLE_KHO_MAY4 TO KHO_MAY4;

-- Giam doc
GRANT SELECT ON MAY4.CHINHANH TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.DANHMUC TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.SANPHAM TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.BIENTHE_SANPHAM TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.VOUCHER TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.NHANVIEN_CN04 TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.DONHANG_CN04 TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.CT_DONHANG_CN04 TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.THANHTOAN_CN04 TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.KHO_CN04_TON TO ROLE_GIAMDOC_MAY4;
GRANT SELECT ON MAY4.KHO_CN04_BANHANG TO ROLE_GIAMDOC_MAY4;

-- Quan ly chi nhanh
GRANT SELECT, INSERT, UPDATE ON MAY4.NHANVIEN_CN04 TO ROLE_QL_MAY4;
GRANT SELECT, INSERT, UPDATE ON MAY4.DONHANG_CN04 TO ROLE_QL_MAY4;
GRANT SELECT, INSERT, UPDATE ON MAY4.CT_DONHANG_CN04 TO ROLE_QL_MAY4;
GRANT SELECT, INSERT, UPDATE ON MAY4.THANHTOAN_CN04 TO ROLE_QL_MAY4;
GRANT SELECT ON MAY4.SANPHAM TO ROLE_QL_MAY4;
GRANT SELECT ON MAY4.BIENTHE_SANPHAM TO ROLE_QL_MAY4;
GRANT SELECT ON MAY4.VOUCHER TO ROLE_QL_MAY4;

-- Nhan vien ban hang
GRANT SELECT ON MAY4.CHINHANH TO ROLE_NV_MAY4;
GRANT SELECT ON MAY4.DANHMUC TO ROLE_NV_MAY4;
GRANT SELECT ON MAY4.SANPHAM TO ROLE_NV_MAY4;
GRANT SELECT ON MAY4.BIENTHE_SANPHAM TO ROLE_NV_MAY4;
GRANT SELECT ON MAY4.VOUCHER TO ROLE_NV_MAY4;
GRANT SELECT ON MAY4.KHO_CN04_TON TO ROLE_NV_MAY4;
GRANT INSERT ON MAY4.DONHANG_CN04 TO ROLE_NV_MAY4;
GRANT INSERT ON MAY4.CT_DONHANG_CN04 TO ROLE_NV_MAY4;
GRANT INSERT ON MAY4.THANHTOAN_CN04 TO ROLE_NV_MAY4;

-- Quan ly kho
GRANT SELECT ON MAY4.SANPHAM TO ROLE_KHO_MAY4;
GRANT SELECT ON MAY4.BIENTHE_SANPHAM TO ROLE_KHO_MAY4;
GRANT SELECT, INSERT, UPDATE ON MAY4.KHO_CN04_TON TO ROLE_KHO_MAY4;
GRANT SELECT, INSERT, UPDATE ON MAY4.KHO_CN04_BANHANG TO ROLE_KHO_MAY4;
-- =====================================================
-- DATABASE LINK TAI MAY4
-- MAY4 ket noi toi MAY1, MAY2, MAY3
-- =====================================================

CREATE PUBLIC DATABASE LINK LINK_MAY4_TO_MAY1
CONNECT TO MAY1 IDENTIFIED BY "123456"
USING 'MAY1';

CREATE PUBLIC DATABASE LINK LINK_MAY4_TO_MAY2
CONNECT TO MAY2 IDENTIFIED BY "123456"
USING 'MAY2';

CREATE PUBLIC DATABASE LINK LINK_MAY4_TO_MAY3
CONNECT TO MAY3 IDENTIFIED BY "123456"
USING 'MAY3';
-- =====================================================
-- CAU TRUY VAN TAI MAY4
-- =====================================================
--Câu 9: TÌm 10 biến thể sản phẩm được bán đủ ở cả 4 chi nhánh- MAY4
SELECT 
    BT.MABT,
    BT.MASP,
    BT.MAU,
    BT.KICHCO
FROM MAY4.BIENTHE_SANPHAM BT
JOIN (
    SELECT MABT
    FROM CT_DONHANG_CN01@LINK_MAY4_TO_MAY1

    INTERSECT

    SELECT MABT
    FROM CT_DONHANG_CN02@LINK_MAY4_TO_MAY2

    INTERSECT

    SELECT MABT
    FROM CT_DONHANG_CN03@LINK_MAY4_TO_MAY3

    INTERSECT

    SELECT MABT
    FROM MAY4.CT_DONHANG_CN04
) X
    ON BT.MABT = X.MABT
ORDER BY BT.MABT
FETCH FIRST 10 ROWS ONLY;
--Câu 10: Tìm 10 khách hàng đã mua hàng ở đủ cả 4 chi nhánh- MAY4
SELECT 
    KH.MAKH,
    KH.HOTEN,
    KH.SODIENTHOAI,
    KH.EMAIL,
    COUNT(DISTINCT DH.MACN) AS SO_CHI_NHANH_DA_MUA
FROM KHACHHANG_TT@LINK_MAY4_TO_MAY1 KH
JOIN (
    SELECT MAKH, MACN
    FROM DONHANG_CN01@LINK_MAY4_TO_MAY1

    UNION ALL

    SELECT MAKH, MACN
    FROM DONHANG_CN02@LINK_MAY4_TO_MAY2

    UNION ALL

    SELECT MAKH, MACN
    FROM DONHANG_CN03@LINK_MAY4_TO_MAY3

    UNION ALL

    SELECT MAKH, MACN
    FROM MAY4.DONHANG_CN04
) DH
    ON KH.MAKH = DH.MAKH
GROUP BY 
    KH.MAKH,
    KH.HOTEN,
    KH.SODIENTHOAI,
    KH.EMAIL
HAVING COUNT(DISTINCT DH.MACN) = 4
ORDER BY KH.MAKH
FETCH FIRST 10 ROWS ONLY;
-- =====================================================
-- Function
-- =====================================================
-- Test case function
SELECT MAY1.FN_TONG_CHI_TIEU_KHACHHANG@LINK_MAY4_TO_MAY1('KH000001') AS TONG_CHI_TIEU
FROM DUAL;
-- =====================================================
-- Stored Procedure
-- =====================================================
-- Test case Stỏed Procedure
BEGIN
    MAY1.PR_CAPNHAT_LUONG_NHANVIEN_TOANHT('NV990001', 12000000);
END;
/
-- =====================================================
-- Trigger
-- =====================================================
-- 1) Trigger: Kiểm tra và cập nhật tông kho khi thêm chi tiết đơn hàng
CREATE OR REPLACE TRIGGER MAY4.TRG_CAPNHAT_KHO_CTDH_CN04
BEFORE INSERT ON MAY4.CT_DONHANG_CN04
FOR EACH ROW
DECLARE
    V_SOLUONGTON MAY4.KHO_CN04_TON.SOLUONGTON%TYPE;
BEGIN
    IF :NEW.MACN <> 'CN04' THEN
        RAISE_APPLICATION_ERROR(-20040, 'Chi tiet don hang CN04 chi duoc co MACN = CN04');
    END IF;

    SELECT SOLUONGTON
    INTO V_SOLUONGTON
    FROM MAY4.KHO_CN04_TON
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT
    FOR UPDATE;

    IF :NEW.SOLUONG > V_SOLUONGTON THEN
        RAISE_APPLICATION_ERROR(-20041, 'So luong ton kho CN04 khong du');
    END IF;

    UPDATE MAY4.KHO_CN04_TON
    SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

    UPDATE MAY4.KHO_CN04_BANHANG
    SET SOLUONGDABAN = SOLUONGDABAN + :NEW.SOLUONG,
        NGAYCAPNHAT = SYSDATE
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20042, 'Khong tim thay bien the san pham trong kho CN04');
END;
/
-- 2) Test case:
INSERT INTO MAY4.CT_DONHANG_CN04
VALUES ('DH04000001', 'CN04', 'BT9999', 5, 150000, 0, 750000);
-- =============================================================================
-- Lost Update
-- =============================================================================
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT MACN, MABT, SOLUONGTON
FROM KHO_CN03_TON@LINK_MAY4_TO_MAY3
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';
--
UPDATE KHO_CN03_TON@LINK_MAY4_TO_MAY3
SET SOLUONGTON = 84
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';

COMMIT;

SELECT MACN, MABT, SOLUONGTON
FROM KHO_CN03_TON@LINK_MAY4_TO_MAY3
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';
-- Cách khắc phục:
UPDATE KHO_CN03_TON@LINK_MAY4_TO_MAY3
SET SOLUONGTON = 84
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';

COMMIT;

-- =============================================================================
-- Deadlock
-- =============================================================================
SELECT MACN, MABT, SOLUONGTON
FROM MAY4.KHO_CN04_TON
WHERE MACN = 'CN04'
  AND MABT = 'BT0006';
--
UPDATE MAY4.KHO_CN04_TON
SET SOLUONGTON = SOLUONGTON - 1
WHERE MACN = 'CN04'
  AND MABT = 'BT0006';
--
UPDATE KHO_CN03_TON@LINK_MAY4_TO_MAY3
SET SOLUONGTON = SOLUONGTON - 1
WHERE MACN = 'CN03'
  AND MABT = 'BT0005';
--
ROLLBACK;
--
SELECT MACN, MABT, SOLUONGTON
FROM MAY4.KHO_CN04_TON
WHERE MACN = 'CN04'
  AND MABT = 'BT0006';