-- ================================================ĐÂY LÀ CHI NHÁNH 3 - MAY 3==================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- ============================================================================================================================================================================
-- =====================================================
-- TAO USER/SCHEMA TAI MAY3 - CHI NHANH DA NANG
-- =====================================================

CREATE USER MAY3 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO MAY3;
GRANT CREATE TABLE TO MAY3;
GRANT CREATE DATABASE LINK TO MAY3;
GRANT CREATE VIEW TO MAY3;
GRANT CREATE PROCEDURE TO MAY3;
GRANT CREATE TRIGGER TO MAY3;
GRANT CREATE SEQUENCE TO MAY3;

ALTER USER MAY3 QUOTA UNLIMITED ON USERS;
-- =====================================================
-- CREATE TABLE SITE MAY3 - CHI NHANH DA NANG - CN03
-- Schema: MAY3
-- =====================================================

CREATE TABLE MAY3.CHINHANH (
    MACN VARCHAR2(10) PRIMARY KEY,
    TENCN VARCHAR2(100) NOT NULL,
    DIACHI VARCHAR2(200),
    SODIENTHOAI VARCHAR2(15),
    THANHPHO VARCHAR2(50) NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY3.DANHMUC (
    MADM VARCHAR2(10) PRIMARY KEY,
    TENDM VARCHAR2(100) NOT NULL,
    MOTA VARCHAR2(255),
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY3.SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    TENSP VARCHAR2(150) NOT NULL,
    MADM VARCHAR2(10) NOT NULL,
    GIABAN NUMBER(12,0) DEFAULT 0 NOT NULL,
    MOTA VARCHAR2(500),
    NGAYTAO DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN3_SP_DM FOREIGN KEY (MADM) REFERENCES MAY3.DANHMUC(MADM)
);

CREATE TABLE MAY3.BIENTHE_SANPHAM (
    MABT VARCHAR2(20) PRIMARY KEY,
    MASP VARCHAR2(20) NOT NULL,
    MAU VARCHAR2(50) NOT NULL,
    KICHCO VARCHAR2(20) NOT NULL,
    SKU VARCHAR2(50) UNIQUE,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_BAN' NOT NULL,
    CONSTRAINT FK_CN3_BT_SP FOREIGN KEY (MASP) REFERENCES MAY3.SANPHAM(MASP)
);

CREATE TABLE MAY3.VOUCHER (
    MAVOUCHER VARCHAR2(20) PRIMARY KEY,
    TENVOUCHER VARCHAR2(100) NOT NULL,
    LOAIGIAMGIA VARCHAR2(20) NOT NULL,
    GIATRIGIAM NUMBER(12,0) DEFAULT 0 NOT NULL,
    DIEUKIENTOITHIEU NUMBER(14,0) DEFAULT 0 NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    SOLUONG NUMBER(10,0) DEFAULT 0 NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'HOAT_DONG' NOT NULL
);

CREATE TABLE MAY3.NHANVIEN_CN03 (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    GIOITINH VARCHAR2(10),
    SODIENTHOAI VARCHAR2(15) UNIQUE,
    EMAIL VARCHAR2(100) UNIQUE,
    CHUCVU VARCHAR2(50) NOT NULL,
    LUONG NUMBER(12,0) DEFAULT 0 NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN03' NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'DANG_LAM' NOT NULL,
    CONSTRAINT FK_CN3_NV_CN FOREIGN KEY (MACN) REFERENCES MAY3.CHINHANH(MACN),
    CONSTRAINT CK_CN3_NV_MACN CHECK (MACN = 'CN03')
);

CREATE TABLE MAY3.DONHANG_CN03 (
    MADH VARCHAR2(30) PRIMARY KEY,
    MAKH VARCHAR2(20) NOT NULL,
    MANV VARCHAR2(20),
    MACN VARCHAR2(10) DEFAULT 'CN03' NOT NULL,
    MAVOUCHER VARCHAR2(20),
    NGAYDAT DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_XAC_NHAN' NOT NULL,
    DIACHINHAN VARCHAR2(200),
    TONGTIENHANG NUMBER(14,0) DEFAULT 0 NOT NULL,
    PHIVANCHUYEN NUMBER(12,0) DEFAULT 0 NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    TONGTHANHTOAN NUMBER(14,0) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CN3_DH_NV FOREIGN KEY (MANV) REFERENCES MAY3.NHANVIEN_CN03(MANV),
    CONSTRAINT FK_CN3_DH_CN FOREIGN KEY (MACN) REFERENCES MAY3.CHINHANH(MACN),
    CONSTRAINT FK_CN3_DH_VC FOREIGN KEY (MAVOUCHER) REFERENCES MAY3.VOUCHER(MAVOUCHER),
    CONSTRAINT CK_CN3_DH_MACN CHECK (MACN = 'CN03'),
    CONSTRAINT CK_CN3_DH_TT CHECK (TRANGTHAI IN ('CHO_XAC_NHAN', 'DANG_XU_LY', 'DANG_GIAO', 'HOAN_THANH', 'DA_HUY'))
);

CREATE TABLE MAY3.CT_DONHANG_CN03 (
    MADH VARCHAR2(30),
    MACN VARCHAR2(10) DEFAULT 'CN03' NOT NULL,
    MABT VARCHAR2(20),
    SOLUONG NUMBER(10,0) NOT NULL,
    DONGIA NUMBER(12,0) NOT NULL,
    GIAMGIA NUMBER(12,0) DEFAULT 0 NOT NULL,
    THANHTIEN NUMBER(14,0) NOT NULL,
    CONSTRAINT PK_CN3_CTDH PRIMARY KEY (MADH, MABT),
    CONSTRAINT FK_CN3_CTDH_DH FOREIGN KEY (MADH) REFERENCES MAY3.DONHANG_CN03(MADH),
    CONSTRAINT FK_CN3_CTDH_BT FOREIGN KEY (MABT) REFERENCES MAY3.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN3_CTDH_MACN CHECK (MACN = 'CN03'),
    CONSTRAINT CK_CN3_CTDH_SL CHECK (SOLUONG > 0)
);

CREATE TABLE MAY3.THANHTOAN_CN03 (
    MATT VARCHAR2(30) PRIMARY KEY,
    MADH VARCHAR2(30) NOT NULL,
    MACN VARCHAR2(10) DEFAULT 'CN03' NOT NULL,
    PHUONGTHUC VARCHAR2(50) NOT NULL,
    SOTIEN NUMBER(14,0) NOT NULL,
    NGAYTHANHTOAN DATE DEFAULT SYSDATE,
    MAGIAODICH VARCHAR2(100) UNIQUE,
    TRANGTHAI VARCHAR2(30) DEFAULT 'CHO_THANH_TOAN' NOT NULL,
    CONSTRAINT FK_CN3_TT_DH FOREIGN KEY (MADH) REFERENCES MAY3.DONHANG_CN03(MADH),
    CONSTRAINT CK_CN3_TT_MACN CHECK (MACN = 'CN03')
);

CREATE TABLE MAY3.KHO_CN03_TON (
    MACN VARCHAR2(10) DEFAULT 'CN03' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGTON NUMBER(10,0) DEFAULT 0 NOT NULL,
    MUCTONTOITHIEU NUMBER(10,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CN3_KHO_TON PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN3_KHO_TON_BT FOREIGN KEY (MABT) REFERENCES MAY3.BIENTHE_SANPHAM(MABT),
    CONSTRAINT CK_CN3_KHO_TON_MACN CHECK (MACN = 'CN03')
);

CREATE TABLE MAY3.KHO_CN03_BANHANG (
    MACN VARCHAR2(10) DEFAULT 'CN03' NOT NULL,
    MABT VARCHAR2(20) NOT NULL,
    SOLUONGDABAN NUMBER(10,0) DEFAULT 0 NOT NULL,
    NGAYCAPNHAT DATE DEFAULT SYSDATE,
    CONSTRAINT PK_CN3_KHO_BH PRIMARY KEY (MACN, MABT),
    CONSTRAINT FK_CN3_KHO_BH_TON FOREIGN KEY (MACN, MABT) REFERENCES MAY3.KHO_CN03_TON(MACN, MABT),
    CONSTRAINT CK_CN3_KHO_BH_MACN CHECK (MACN = 'CN03')
);
-- =====================================================
-- INSERT DATA SITE MAY3 - CN03 - DA NANG
-- Schema: MAY3
-- =====================================================

INSERT INTO MAY3.CHINHANH VALUES ('CN01', 'Chi nhanh TP.HCM', 'Quan 1, TP.HCM', '0901000001', 'TP.HCM', 'HOAT_DONG');
INSERT INTO MAY3.CHINHANH VALUES ('CN02', 'Chi nhanh Ha Noi', 'Quan Hoan Kiem, Ha Noi', '0901000002', 'Ha Noi', 'HOAT_DONG');
INSERT INTO MAY3.CHINHANH VALUES ('CN03', 'Chi nhanh Da Nang', 'Quan Hai Chau, Da Nang', '0901000003', 'Da Nang', 'HOAT_DONG');
INSERT INTO MAY3.CHINHANH VALUES ('CN04', 'Chi nhanh Can Tho', 'Quan Ninh Kieu, Can Tho', '0901000004', 'Can Tho', 'HOAT_DONG');

INSERT INTO MAY3.DANHMUC VALUES ('DM01', 'Ao thun', 'Danh muc ao thun', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM02', 'Ao so mi', 'Danh muc ao so mi', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM03', 'Ao khoac', 'Danh muc ao khoac', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM04', 'Quan dai', 'Danh muc quan dai', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM05', 'Quan ngan', 'Danh muc quan ngan', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM06', 'Vay', 'Danh muc vay', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM07', 'Dam', 'Danh muc dam', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM08', 'Phu kien', 'Danh muc phu kien', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM09', 'Giay dep', 'Danh muc giay dep', 'HOAT_DONG');
INSERT INTO MAY3.DANHMUC VALUES ('DM10', 'Tui xach', 'Danh muc tui xach', 'HOAT_DONG');

INSERT INTO MAY3.SANPHAM (MASP, TENSP, MADM, GIABAN, MOTA, NGAYTAO, TRANGTHAI)
SELECT 'SP' || LPAD(LEVEL, 4, '0'),
       'San pham thoi trang ' || LEVEL,
       'DM' || LPAD(MOD(LEVEL - 1, 10) + 1, 2, '0'),
       100000 + MOD(LEVEL, 50) * 10000,
       'Mo ta san pham ' || LEVEL,
       SYSDATE,
       'DANG_BAN'
FROM DUAL CONNECT BY LEVEL <= 200;

INSERT INTO MAY3.BIENTHE_SANPHAM (MABT, MASP, MAU, KICHCO, SKU, TRANGTHAI)
SELECT 'BT' || LPAD(LEVEL, 4, '0'),
       'SP' || LPAD(MOD(LEVEL - 1, 200) + 1, 4, '0'),
       CASE MOD(LEVEL, 5) WHEN 0 THEN 'DEN' WHEN 1 THEN 'TRANG' WHEN 2 THEN 'DO' WHEN 3 THEN 'XANH' ELSE 'BE' END,
       CASE MOD(LEVEL, 5) WHEN 0 THEN 'S' WHEN 1 THEN 'M' WHEN 2 THEN 'L' WHEN 3 THEN 'XL' ELSE 'XXL' END,
       'SKU_CN03_' || LPAD(LEVEL, 4, '0'),
       'DANG_BAN'
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO MAY3.VOUCHER (
    MAVOUCHER, TENVOUCHER, LOAIGIAMGIA, GIATRIGIAM, DIEUKIENTOITHIEU,
    NGAYBATDAU, NGAYKETTHUC, SOLUONG, TRANGTHAI
)
SELECT 'VC' || LPAD(LEVEL, 3, '0'),
       'Voucher giam gia ' || LEVEL,
       CASE WHEN MOD(LEVEL, 2) = 0 THEN 'TIEN' ELSE 'PHAN_TRAM' END,
       CASE WHEN MOD(LEVEL, 2) = 0 THEN 20000 + LEVEL * 1000 ELSE 5 + MOD(LEVEL, 20) END,
       100000,
       DATE '2026-01-01',
       DATE '2026-12-31',
       1000,
       'HOAT_DONG'
FROM DUAL CONNECT BY LEVEL <= 20;

INSERT INTO MAY3.NHANVIEN_CN03 (MANV, HOTEN, GIOITINH, SODIENTHOAI, EMAIL, CHUCVU, LUONG, MACN, TRANGTHAI)
SELECT
    'NV03' || LPAD(LEVEL, 4, '0'),
    'Nhan vien CN03 ' || LEVEL,
    CASE MOD(LEVEL, 3) WHEN 0 THEN 'NAM' WHEN 1 THEN 'NU' ELSE 'KHAC' END,
    '094' || LPAD(LEVEL, 7, '0'),
    'nvcn03_' || LEVEL || '@shop.com',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'QUAN_LY' ELSE 'NHAN_VIEN' END,
    7000000 + MOD(LEVEL, 10) * 500000,
    'CN03',
    'DANG_LAM'
FROM DUAL CONNECT BY LEVEL <= 50;

INSERT INTO MAY3.KHO_CN03_TON (MACN, MABT, SOLUONGTON, MUCTONTOITHIEU)
SELECT 'CN03', 'BT' || LPAD(LEVEL, 4, '0'), 100 + MOD(LEVEL, 200), 10
FROM DUAL CONNECT BY LEVEL <= 1000;

INSERT INTO MAY3.KHO_CN03_BANHANG (MACN, MABT, SOLUONGDABAN, NGAYCAPNHAT)
SELECT MACN, MABT, MOD(TO_NUMBER(SUBSTR(MABT, 3)), 50), SYSDATE
FROM MAY3.KHO_CN03_TON;

INSERT INTO MAY3.DONHANG_CN03 (
    MADH, MAKH, MANV, MACN, MAVOUCHER, NGAYDAT, TRANGTHAI, DIACHINHAN,
    TONGTIENHANG, PHIVANCHUYEN, GIAMGIA, TONGTHANHTOAN
)
SELECT
    'DH03' || LPAD(LEVEL, 6, '0'),
    'KH' || LPAD(MOD(LEVEL - 1, 1000) + 1, 6, '0'),
    'NV03' || LPAD(MOD(LEVEL - 1, 50) + 1, 4, '0'),
    'CN03',
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 'VC' || LPAD(MOD(LEVEL - 1, 20) + 1, 3, '0') ELSE NULL END,
    SYSDATE - MOD(LEVEL, 90),
    CASE MOD(LEVEL, 5)
        WHEN 0 THEN 'HOAN_THANH'
        WHEN 1 THEN 'CHO_XAC_NHAN'
        WHEN 2 THEN 'DANG_XU_LY'
        WHEN 3 THEN 'DANG_GIAO'
        ELSE 'DA_HUY'
    END,
    'Dia chi nhan hang CN03 ' || LEVEL,
    300000 + MOD(LEVEL, 20) * 10000,
    30000,
    CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END
FROM DUAL
CONNECT BY LEVEL <= 250;

INSERT INTO MAY3.CT_DONHANG_CN03 (MADH, MACN, MABT, SOLUONG, DONGIA, GIAMGIA, THANHTIEN)
SELECT
    'DH03' || LPAD(ORDER_NO, 6, '0'),
    'CN03',
    'BT' || LPAD(MOD(ORDER_NO * 2 + ITEM_NO, 1000) + 1, 4, '0'),
    MOD(ORDER_NO + ITEM_NO, 3) + 1,
    100000 + ITEM_NO * 50000,
    0,
    (MOD(ORDER_NO + ITEM_NO, 3) + 1) * (100000 + ITEM_NO * 50000)
FROM (
    SELECT CEIL(LEVEL / 2) AS ORDER_NO,
           MOD(LEVEL - 1, 2) + 1 AS ITEM_NO
    FROM DUAL CONNECT BY LEVEL <= 500
);

INSERT INTO MAY3.THANHTOAN_CN03 (MATT, MADH, MACN, PHUONGTHUC, SOTIEN, NGAYTHANHTOAN, MAGIAODICH, TRANGTHAI)
SELECT
    'TT03' || LPAD(LEVEL, 6, '0'),
    'DH03' || LPAD(LEVEL, 6, '0'),
    'CN03',
    CASE MOD(LEVEL, 4) WHEN 0 THEN 'TIEN_MAT' WHEN 1 THEN 'CHUYEN_KHOAN' WHEN 2 THEN 'THE' ELSE 'VI_DIEN_TU' END,
    300000 + MOD(LEVEL, 20) * 10000 + 30000 - CASE WHEN MOD(LEVEL, 5) = 0 THEN 20000 ELSE 0 END,
    SYSDATE - MOD(LEVEL, 90),
    'MGD03' || LPAD(LEVEL, 6, '0'),
    CASE WHEN MOD(LEVEL, 5) = 4 THEN 'CHO_THANH_TOAN' ELSE 'DA_THANH_TOAN' END
FROM DUAL
CONNECT BY LEVEL <= 250;

COMMIT;
-- =====================================================
-- PHAN QUYEN NGHIEP VU TAI MAY3 - CHI NHANH CN03
-- Schema chinh: MAY3
-- =====================================================

CREATE USER GD_MAY3 IDENTIFIED BY "123456";
CREATE USER QL_MAY3 IDENTIFIED BY "123456";
CREATE USER NV_MAY3 IDENTIFIED BY "123456";
CREATE USER KHO_MAY3 IDENTIFIED BY "123456";

GRANT CREATE SESSION TO GD_MAY3;
GRANT CREATE SESSION TO QL_MAY3;
GRANT CREATE SESSION TO NV_MAY3;
GRANT CREATE SESSION TO KHO_MAY3;

GRANT CREATE DATABASE LINK TO GD_MAY3;

CREATE ROLE ROLE_GIAMDOC_MAY3;
CREATE ROLE ROLE_QL_MAY3;
CREATE ROLE ROLE_NV_MAY3;
CREATE ROLE ROLE_KHO_MAY3;

GRANT ROLE_GIAMDOC_MAY3 TO GD_MAY3;
GRANT ROLE_QL_MAY3 TO QL_MAY3;
GRANT ROLE_NV_MAY3 TO NV_MAY3;
GRANT ROLE_KHO_MAY3 TO KHO_MAY3;

-- Giam doc
GRANT SELECT ON MAY3.CHINHANH TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.DANHMUC TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.SANPHAM TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.BIENTHE_SANPHAM TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.VOUCHER TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.NHANVIEN_CN03 TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.DONHANG_CN03 TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.CT_DONHANG_CN03 TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.THANHTOAN_CN03 TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.KHO_CN03_TON TO ROLE_GIAMDOC_MAY3;
GRANT SELECT ON MAY3.KHO_CN03_BANHANG TO ROLE_GIAMDOC_MAY3;

-- Quan ly chi nhanh
GRANT SELECT, INSERT, UPDATE ON MAY3.NHANVIEN_CN03 TO ROLE_QL_MAY3;
GRANT SELECT, INSERT, UPDATE ON MAY3.DONHANG_CN03 TO ROLE_QL_MAY3;
GRANT SELECT, INSERT, UPDATE ON MAY3.CT_DONHANG_CN03 TO ROLE_QL_MAY3;
GRANT SELECT, INSERT, UPDATE ON MAY3.THANHTOAN_CN03 TO ROLE_QL_MAY3;
GRANT SELECT ON MAY3.SANPHAM TO ROLE_QL_MAY3;
GRANT SELECT ON MAY3.BIENTHE_SANPHAM TO ROLE_QL_MAY3;
GRANT SELECT ON MAY3.VOUCHER TO ROLE_QL_MAY3;

-- Nhan vien ban hang
GRANT SELECT ON MAY3.CHINHANH TO ROLE_NV_MAY3;
GRANT SELECT ON MAY3.DANHMUC TO ROLE_NV_MAY3;
GRANT SELECT ON MAY3.SANPHAM TO ROLE_NV_MAY3;
GRANT SELECT ON MAY3.BIENTHE_SANPHAM TO ROLE_NV_MAY3;
GRANT SELECT ON MAY3.VOUCHER TO ROLE_NV_MAY3;
GRANT SELECT ON MAY3.KHO_CN03_TON TO ROLE_NV_MAY3;
GRANT INSERT ON MAY3.DONHANG_CN03 TO ROLE_NV_MAY3;
GRANT INSERT ON MAY3.CT_DONHANG_CN03 TO ROLE_NV_MAY3;
GRANT INSERT ON MAY3.THANHTOAN_CN03 TO ROLE_NV_MAY3;

-- Quan ly kho
GRANT SELECT ON MAY3.SANPHAM TO ROLE_KHO_MAY3;
GRANT SELECT ON MAY3.BIENTHE_SANPHAM TO ROLE_KHO_MAY3;
GRANT SELECT, INSERT, UPDATE ON MAY3.KHO_CN03_TON TO ROLE_KHO_MAY3;
GRANT SELECT, INSERT, UPDATE ON MAY3.KHO_CN03_BANHANG TO ROLE_KHO_MAY3;
-- =====================================================
-- DATABASE LINK TAI MAY3
-- MAY3 ket noi toi MAY1, MAY2, MAY4
-- =====================================================

CREATE PUBLIC DATABASE LINK LINK_MAY3_TO_MAY1
CONNECT TO MAY1 IDENTIFIED BY "123456"
USING 'MAY1';

CREATE PUBLIC DATABASE LINK LINK_MAY3_TO_MAY2
CONNECT TO MAY2 IDENTIFIED BY "123456"
USING 'MAY2';

CREATE PUBLIC DATABASE LINK LINK_MAY3_TO_MAY4
CONNECT TO MAY4 IDENTIFIED BY "123456"
USING 'MAY4';
-- =====================================================
-- CAU TRUY VAN TAI MAY3
-- =====================================================
--Câu 7: Tìm  10 biến thể sản phẩm đã bán ở cả MAY1 và MAY3-MAY3
SELECT 
    BT.MABT,
    BT.MASP,
    BT.MAU,
    BT.KICHCO
FROM MAY3.BIENTHE_SANPHAM BT
JOIN (
    SELECT MABT
    FROM CT_DONHANG_CN01@LINK_MAY3_TO_MAY1

    INTERSECT

    SELECT MABT
    FROM MAY3.CT_DONHANG_CN03
) X
    ON BT.MABT = X.MABT
ORDER BY BT.MABT
FETCH FIRST 10 ROWS ONLY;
--Câu 8: Tìm 10 biến thể có trong kho MAY3 nhưng chưa từng bán ở cả 4 chi nhánh-MAY3
SELECT 
    BT.MABT,
    BT.MASP,
    BT.MAU,
    BT.KICHCO,
    KHO.SOLUONGTON
FROM MAY3.BIENTHE_SANPHAM BT
JOIN MAY3.KHO_CN03_TON KHO
    ON BT.MABT = KHO.MABT
JOIN (
    SELECT MABT
    FROM MAY3.KHO_CN03_TON

    MINUS

    SELECT MABT
    FROM (
        SELECT MABT
        FROM CT_DONHANG_CN01@LINK_MAY3_TO_MAY1

        UNION

        SELECT MABT
        FROM CT_DONHANG_CN02@LINK_MAY3_TO_MAY2

        UNION

        SELECT MABT
        FROM MAY3.CT_DONHANG_CN03

        UNION

        SELECT MABT
        FROM CT_DONHANG_CN04@LINK_MAY3_TO_MAY4
    )
) X
    ON BT.MABT = X.MABT
ORDER BY BT.MABT
FETCH FIRST 10 ROWS ONLY;
-- =====================================================
-- Function
-- =====================================================
-- Test case function
SELECT MAY1.FN_TONG_CHI_TIEU_KHACHHANG@LINK_MAY3_TO_MAY1('KH000001') AS TONG_CHI_TIEU
FROM DUAL;
-- =====================================================
-- Stored Procedure
-- =====================================================
-- Test case Stỏed Procedure
SELECT MANV, HOTEN, LUONG
FROM NHANVIEN_CN03@LINK_MAY1_TO_MAY3
WHERE MANV = 'NV030001';
--
BEGIN
    MAY1.PR_CAPNHAT_LUONG_NHANVIEN_TOANHT('NV030001', 7000000);
END;
/
--
SELECT MANV, HOTEN, LUONG
FROM NHANVIEN_CN03@LINK_MAY1_TO_MAY3
WHERE MANV = 'NV030001';
-- =====================================================
-- Trigger
-- =====================================================
-- 1) Trigger: Kiểm tra và cập nhật tông kho khi thêm chi tiết đơn hàng
CREATE OR REPLACE TRIGGER MAY3.TRG_CAPNHAT_KHO_CTDH_CN03
BEFORE INSERT ON MAY3.CT_DONHANG_CN03
FOR EACH ROW
DECLARE
    V_SOLUONGTON MAY3.KHO_CN03_TON.SOLUONGTON%TYPE;
BEGIN
    IF :NEW.MACN <> 'CN03' THEN
        RAISE_APPLICATION_ERROR(-20030, 'Chi tiet don hang CN03 chi duoc co MACN = CN03');
    END IF;

    SELECT SOLUONGTON
    INTO V_SOLUONGTON
    FROM MAY3.KHO_CN03_TON
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT
    FOR UPDATE;

    IF :NEW.SOLUONG > V_SOLUONGTON THEN
        RAISE_APPLICATION_ERROR(-20031, 'So luong ton kho CN03 khong du');
    END IF;

    UPDATE MAY3.KHO_CN03_TON
    SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

    UPDATE MAY3.KHO_CN03_BANHANG
    SET SOLUONGDABAN = SOLUONGDABAN + :NEW.SOLUONG,
        NGAYCAPNHAT = SYSDATE
    WHERE MACN = :NEW.MACN
      AND MABT = :NEW.MABT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20032, 'Khong tim thay bien the san pham trong kho CN03');
END;
/
-- 2) Test case:
SELECT MACN, MABT, SOLUONGTON
FROM MAY3.KHO_CN03_TON
WHERE MACN = 'CN03'
  AND MABT = 'BT0997';
--
INSERT INTO MAY3.CT_DONHANG_CN03
VALUES ('DH03000001', 'CN03', 'BT0997', 99999, 150000, 0, 14999850000);
-- =============================================================================
-- Phantom Read 
-- =============================================================================
INSERT INTO DONHANG_CN02@LINK_MAY3_TO_MAY2 (
    MADH, MAKH, MANV, MACN, MAVOUCHER, NGAYDAT, TRANGTHAI, DIACHINHAN,
    TONGTIENHANG, PHIVANCHUYEN, GIAMGIA, TONGTHANHTOAN
)
VALUES (
    'DH02TEST01',
    'KH000001',
    'NV020001',
    'CN02',
    NULL,
    SYSDATE,
    'CHO_XAC_NHAN',
    'Dia chi test phantom read',
    300000,
    30000,
    0,
    330000
);

COMMIT;
-- Cách khắc phục
INSERT INTO DONHANG_CN02@LINK_MAY3_TO_MAY2 (
    MADH, MAKH, MANV, MACN, MAVOUCHER, NGAYDAT, TRANGTHAI, DIACHINHAN,
    TONGTIENHANG, PHIVANCHUYEN, GIAMGIA, TONGTHANHTOAN
)
VALUES (
    'DH02TEST02',
    'KH000001',
    'NV020001',
    'CN02',
    NULL,
    SYSDATE,
    'CHO_XAC_NHAN',
    'Dia chi test serializable',
    300000,
    30000,
    0,
    330000
);

COMMIT;
-- =============================================================================
-- Lost Update
-- =============================================================================
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT MACN, MABT, SOLUONGTON
FROM MAY3.KHO_CN03_TON
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';
--
UPDATE MAY3.KHO_CN03_TON
SET SOLUONGTON = 94
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';

COMMIT;

SELECT MACN, MABT, SOLUONGTON
FROM MAY3.KHO_CN03_TON
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';
-- Cách khắc phục
UPDATE MAY3.KHO_CN03_TON
SET SOLUONGTON = 104
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';

COMMIT;
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SELECT MACN, MABT, SOLUONGTON
FROM MAY3.KHO_CN03_TON
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';
--
UPDATE MAY3.KHO_CN03_TON
SET SOLUONGTON = 94
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';
--
ROLLBACK;
--
UPDATE MAY3.KHO_CN03_TON
SET SOLUONGTON = 104
WHERE MACN = 'CN03'
  AND MABT = 'BT0004';

COMMIT;
-- =============================================================================
-- Deadlock
-- =============================================================================
SELECT MACN, MABT, SOLUONGTON
FROM MAY3.KHO_CN03_TON
WHERE MACN = 'CN03'
  AND MABT = 'BT0005';
--
UPDATE MAY3.KHO_CN03_TON
SET SOLUONGTON = SOLUONGTON - 1
WHERE MACN = 'CN03'
  AND MABT = 'BT0005';
--
UPDATE KHO_CN04_TON@LINK_MAY3_TO_MAY4
SET SOLUONGTON = SOLUONGTON - 1
WHERE MACN = 'CN04'
  AND MABT = 'BT0006';
--
ROLLBACK;
--
SELECT MACN, MABT, SOLUONGTON
FROM MAY3.KHO_CN03_TON
WHERE MACN = 'CN03'
  AND MABT = 'BT0005';
-- =============================================================================
-- Tối ưu câu truy vấn
-- =============================================================================
-- Câu truy vấn chưa tối ưu
SELECT 
    MACN,
    COUNT(*) AS SO_DON_HOAN_THANH,
    SUM(TONGTHANHTOAN) AS TONG_DOANH_THU,
    ROUND(AVG(TONGTHANHTOAN), 0) AS DOANH_THU_TRUNG_BINH
FROM (
    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM MAY3.DONHANG_CN03

    UNION ALL

    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY3_TO_MAY4
)
WHERE TRANGTHAI = 'HOAN_THANH'
GROUP BY MACN
ORDER BY MACN;
-- Explain câu truy vấn chưa tối ưu:
EXPLAIN PLAN FOR
SELECT 
    MACN,
    COUNT(*) AS SO_DON_HOAN_THANH,
    SUM(TONGTHANHTOAN) AS TONG_DOANH_THU,
    ROUND(AVG(TONGTHANHTOAN), 0) AS DOANH_THU_TRUNG_BINH
FROM (
    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM MAY3.DONHANG_CN03

    UNION ALL

    SELECT MACN, TRANGTHAI, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY3_TO_MAY4
)
WHERE TRANGTHAI = 'HOAN_THANH'
GROUP BY MACN
ORDER BY MACN;
-- Xem lại kết quả:
SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);
-- Câu truy vấn tối ưu:
SELECT 
    MACN,
    COUNT(*) AS SO_DON_HOAN_THANH,
    SUM(TONGTHANHTOAN) AS TONG_DOANH_THU,
    ROUND(AVG(TONGTHANHTOAN), 0) AS DOANH_THU_TRUNG_BINH
FROM (
    SELECT MACN, TONGTHANHTOAN
    FROM MAY3.DONHANG_CN03
    WHERE TRANGTHAI = 'HOAN_THANH'

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY3_TO_MAY4
    WHERE TRANGTHAI = 'HOAN_THANH'
)
GROUP BY MACN
ORDER BY MACN;
-- Explain câu truy vấn tối ưu:
EXPLAIN PLAN FOR
SELECT 
    MACN,
    COUNT(*) AS SO_DON_HOAN_THANH,
    SUM(TONGTHANHTOAN) AS TONG_DOANH_THU,
    ROUND(AVG(TONGTHANHTOAN), 0) AS DOANH_THU_TRUNG_BINH
FROM (
    SELECT MACN, TONGTHANHTOAN
    FROM MAY3.DONHANG_CN03
    WHERE TRANGTHAI = 'HOAN_THANH'

    UNION ALL

    SELECT MACN, TONGTHANHTOAN
    FROM DONHANG_CN04@LINK_MAY3_TO_MAY4
    WHERE TRANGTHAI = 'HOAN_THANH'
)
GROUP BY MACN
ORDER BY MACN;
-- Xem lại kết quả:
SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);
-- Kiểm tra số dòng trước và sau khi lọc:
-- MAY3:
SELECT 
    'MAY3_DONHANG_CN03' AS BANG,
    COUNT(*) AS TONG_SO_DONG,
    SUM(CASE WHEN TRANGTHAI = 'HOAN_THANH' THEN 1 ELSE 0 END) AS SO_DONG_CAN_LAY
FROM MAY3.DONHANG_CN03;
-- MAY4:
SELECT 
    'MAY4_DONHANG_CN04' AS BANG,
    COUNT(*) AS TONG_SO_DONG,
    SUM(CASE WHEN TRANGTHAI = 'HOAN_THANH' THEN 1 ELSE 0 END) AS SO_DONG_CAN_LAY
FROM DONHANG_CN04@LINK_MAY3_TO_MAY4;
